In [62]:
import requests
from bs4 import BeautifulSoup, Comment
import pandas as pd

In [24]:
#translating the scraping better for better scalability
url = 'https://www.pro-football-reference.com/teams/clt/2004.htm' 
response = requests.get(url)
print(response.status_code)

200

In [25]:
#Colts statistics page
text2 = BeautifulSoup(response.content, 'html.parser')

In [63]:
table_ids = [table.get("id") for table in text2.find_all("table") if table.get("id")]
print(table_ids)

['team_stats', 'games', 'team_conversions', 'passing', 'passing_post', 'rushing_and_receiving', 'rushing_and_receiving_post', 'defense', 'defense_post']

In [56]:
all_rows["passing"]

[<tr> <th aria-label="Rk" class="ranker poptip center" data-stat="ranker" data-tip="Rank" scope="col">Rk</th> <th aria-label="Player" class="poptip sort_default_asc center" data-stat="name_display" scope="col">Player</th> <th aria-label="Age" class="poptip center" data-stat="age" data-tip="As of Dec. 31 of the season in question." scope="col">Age</th> <th aria-label="Pos" class="poptip center" data-stat="pos" data-tip="Position" scope="col">Pos</th> <th aria-label="G" class="poptip center" data-stat="games" data-tip="Games played" scope="col">G</th> <th aria-label="GS" class="poptip center" data-stat="games_started" data-tip="Games started as an offensive or defensive player" scope="col">GS</th> <th aria-label="QBrec" class="poptip center" data-stat="qb_rec" data-tip="Team record in games started by this QB (regular season)" scope="col">QBrec</th> <th aria-label="Cmp" class="poptip center" data-stat="pass_cmp" data-tip="Passes completed" scope="col">Cmp</th> <th aria-label="Att" class="poptip center" data-stat="pass_att" data-tip="Passes attempted" scope="col">Att</th> <th aria-label="Cmp%" class="poptip hide_non_quals center" data-filter="1" data-name="" data-stat="pass_cmp_pct" data-tip="Percentage of Passes Completed&lt;br&gt;Minimum 14 attempts per scheduled game to qualify as leader.&lt;br /&gt;Minimum 1500 pass attempts to qualify as career leader." scope="col">Cmp%</th> <th aria-label="Yds" class="poptip center" data-stat="pass_yds" data-tip="Yards Gained by Passing&lt;br&gt;For teams, sack yardage is deducted from this total" scope="col">Yds</th> <th aria-label="TD" class="poptip center" data-stat="pass_td" data-tip="Passing Touchdowns" scope="col">TD</th> <th aria-label="TD%" class="poptip hide_non_quals center" data-filter="1" data-name="" data-stat="pass_td_pct" data-tip="Percentage of Touchdowns Thrown when Attempting to Pass &lt;br&gt;Minimum 14 attempts per scheduled game to qualify as leader.&lt;br /&gt;Minimum 1500 pass attempts to qualify as career leader" scope="col">TD%</th> <th aria-label="Int" class="poptip center" data-stat="pass_int" data-tip="Interceptions thrown" scope="col">Int</th> <th aria-label="Int%" class="poptip hide_non_quals center" data-filter="1" data-name="" data-stat="pass_int_pct" data-tip="Percentage of Times Intercepted when Attempting to Pass &lt;br&gt;Minimum 14 attempts per scheduled game to qualify as leader.&lt;br /&gt;Minimum 1500 pass attempts to qualify as career leader.&lt;br /&gt;" scope="col">Int%</th> <th aria-label="1D" class="poptip center" data-stat="pass_first_down" data-tip="First downs passing" scope="col">1D</th> <th aria-label="Succ%" class="poptip hide_non_quals center" data-filter="1" data-name="" data-stat="pass_success" data-tip="Passing Success Rate&lt;br /&gt;A successful pass gains at least 40% of yards required on 1st down, 60% of yards required on 2nd down, and 100% on 3rd or 4th down. Denominator is pass attempts + times sacked." scope="col">Succ%</th> <th aria-label="Lng" class="poptip center" data-stat="pass_long" data-tip="Longest Completed Pass Thrown (complete since 1975)" scope="col">Lng</th> <th aria-label="Y/A" class="poptip hide_non_quals center" data-filter="1" data-name="" data-stat="pass_yds_per_att" data-tip="Yards gained per pass attempt &lt;br&gt;Minimum 14 attempts per scheduled game to qualify as leader.&lt;br&gt;Minimum 1500 pass attempts to qualify as career leader." scope="col">Y/A</th> <th aria-label="AY/A" class="poptip hide_non_quals center" data-filter="1" data-name="" data-stat="pass_adj_yds_per_att" data-tip="Adjusted Yards gained per pass attempt&lt;br /&gt;(Passing Yards + 20 * Passing TD - 45 * Interceptions) / (Passes Attempted)&lt;br /&gt;Minimum 14 attempts per scheduled game to qualify as leader.&lt;br /&gt;Minimum 1500 pass attempts to qualify as career leader." scope="col">AY/A</th> <th aria-label="Y/C" class="poptip hide_non_quals center" data-filter="1" data-name="" data-stat="pass_yds_per_cmp" data-tip="&lt;b&gt;Yards gained per pass completion&lt;/b&gt; (Passing Yards) / (Passes Completed)&lt;br /&gt;Minimum 14 pass attempts per schedule game to qualify as leader.&lt;br /&gt;Minimum 1500 pass attempts to qualify as career leader" scope="col">Y/C</th> <th aria-label="Y/G" class="poptip hide_non_quals center" data-filter="1" data-name="" data-stat="pass_yds_per_g" data-tip="&lt;b&gt;Yards gained per game played&lt;/b&gt;&lt;br&gt;Minimum half a game played per scheduled game to qualify as leader.&lt;br&gt;Minimum 1500 pass attempts to qualify as career leader" scope="col">Y/G</th> <th aria-label="Rate" class="poptip hide_non_quals center" data-filter="1" data-name="" data-stat="pass_rating" data-tip="Passer Rating, &lt;a href='https://www.pro-football-reference.com/about/glossary.htm'&gt;see glossary&lt;/a&gt; for details&lt;br&gt;Different ratings are used by the NFL and NCAA.&lt;br /&gt;Minimum 1500 pass attempts to qualify as career leader, minimum 150 pass attempts for playoffs leader." scope="col">Rate</th> <th aria-label="Sk" class="poptip center" data-stat="pass_sacked" data-tip="Times sacked (first recorded in 1969, player per game since 1981)" scope="col">Sk</th> <th aria-label="Yds" class="poptip center" data-stat="pass_sacked_yds" data-tip="Yards lost due to sacks (first recorded in 1969, player per game since 1981)" scope="col">Yds</th> <th aria-label="Sk%" class="poptip hide_non_quals center" data-filter="1" data-name="" data-stat="pass_sacked_pct" data-tip="Percentage of Time Sacked when Attempting to Pass: Times Sacked / (Passes Attempted + Times Sacked)&lt;br&gt;Minimum 14 attempts + sacks per scheduled game to qualify as leader.&lt;br /&gt;Minimum 1500 pass attempts to qualify as career leader" scope="col">Sk%</th> <th aria-label="NY/A" class="poptip hide_non_quals center" data-filter="1" data-name="" data-stat="pass_net_yds_per_att" data-tip="Net Yards gained per pass attempt&lt;br /&gt;(Passing Yards - Sack Yards) / (Passes Attempted + Times Sacked)&lt;br /&gt;Minimum 14 attempts per schedule game to qualify as leader.&lt;br /&gt;Minimum 1500 pass attempts to qualify as career leader." scope="col">NY/A</th> <th aria-label="ANY/A" class="poptip hide_non_quals center" data-filter="1" data-name="" data-stat="pass_adj_net_yds_per_att" data-tip="&lt;b&gt;Adjusted Net Yards per Pass Attempt&lt;/b&gt;&lt;br&gt;(Passing Yards - Sack Yards + (20 * Passing TD) - (45 * Interceptions)) / (Passes Attempted + Times Sacked)&lt;br&gt;Minimum 14 attempts per scheduled game to qualify as leader.&lt;br /&gt;Minimum 1500 pass attempts to qualify as career leader." scope="col">ANY/A</th> <th aria-label="4QC" class="poptip center" data-stat="comebacks" data-tip="Comebacks led by quarterback.&lt;br /&gt;Must be an offensive scoring drive in the 4th quarter, with the team trailing by one score, though not necessarily a drive to take the lead. Only games ending in a win or tie are included." scope="col">4QC</th> <th aria-label="GWD" class="poptip center" data-stat="gwd" data-tip="Game-winning drives led by quarterback.&lt;br /&gt;Must be an offensive scoring drive in the 4th quarter or overtime that puts the winning team ahead for the last time." scope="col">GWD</th> <th aria-label="Awards" class="poptip sort_default_asc center" data-stat="awards" scope="col">Awards</th> </tr>,
 <tr> <th class="right" csk="1" data-stat="ranker" scope="row">1</th> <td class="left" csk="Manning Peyton-0" data-append-csv="MannPe00" data-stat="name_display"><a href="/players/M/MannPe00.htm">Peyton Manning</a></td> <td class="right" data-stat="age">28</td> <td class="left" data-stat="pos">QB</td> <td class="right" data-stat="games">16</td> <td class="right" data-stat="games_started">16</td> <td class="right" csk="0.75000000000" data-stat="qb_rec">12-4-0</td> <td class="right" data-stat="pass_cmp">336</td> <td class="right" data-stat="pass_att">497</td> <td class="right" csk="0.6760563380" data-stat="pass_cmp_pct">67.6</td> <td class="right" data-stat="pass_yds">4557</td> <td class="right" data-stat="pass_td"><strong>49</strong></td> <td class="right" csk="0.0985915493" data-stat="pass_td_pct"><strong>9.9</strong></td> <td class="right" data-stat="pass_int">10</td> <td class="right" csk="0.0201207243" data-stat="pass_int_pct">2.0</td> <td class="right" data-stat="pass_first_down">233</td> <td class="right" csk="0.5705882353" data-stat="pass_success">57.1</td> <td class="right" data-stat="pass_long">80</td> <td class="right" csk="9.1690140845" data-stat="pass_yds_per_att"><strong>9.2</strong></td> <td class="right" csk="10.23541247485" data-stat="pass_adj_yds_per_att"><strong>10.24</strong></td> <td class="right" csk="13.5625000000" data-stat="pass_yds_per_cmp"><strong>13.6</strong></td> <td class="right" csk="284.8125000000" data-stat="pass_yds_per_g">284.8</td> <td class="right" csk="121.1" data-stat="pass_rating"><strong>121.1</strong></td> <td class="right" data-stat="pass_sacked">13</td> <td class="right" data-stat="pass_sacked_yds">101</td> <td class="right" csk="0.0254901961" data-stat="pass_sacked_pct">2.55</td> <td class="right" csk="8.7372549020" data-stat="pass_net_yds_per_att"><strong>8.74</strong></td> <td class="right" csk="9.77647058824" data-stat="pass_adj_net_yds_per_att"><strong>9.78</strong></td> <td class="right" data-stat="comebacks">2</td> <td class="right" data-stat="gwd">4</td> <td class="left" data-stat="awards"><a href="/years/2004/probowl.htm">PB</a>,<b><a href="/years/2004/allpro.htm">AP-1</a></b>,<b><a href="/awards/awards_2004.htm">AP MVP-1</a></b>,<b><a href="/awards/awards_2004.htm">AP OPoY-1</a></b></td> </tr>,
 <tr> <th class="right" csk="2" data-stat="ranker" scope="row">2</th> <td class="left" csk="Sorgi Jim-0" data-append-csv="SorgJi00" data-stat="name_display"><a href="/players/S/SorgJi00.htm">Jim Sorgi</a></td> <td class="right" data-stat="age">24</td> <td class="left" data-stat="pos">QB</td> <td class="right" data-stat="games">4</td> <td class="right iz" data-stat="games_started">0</td> <td class="right" data-stat="qb_rec"></td> <td class="right" data-stat="pass_cmp">17</td> <td class="right" data-stat="pass_att">29</td> <td class="right" csk="0.5862068966" data-stat="pass_cmp_pct">58.6</td> <td class="right" data-stat="pass_yds">175</td> <td class="right" data-stat="pass_td">2</td> <td class="right" csk="0.0689655172" data-stat="pass_td_pct">6.9</td> <td class="right iz" data-stat="pass_int">0</td> <td class="right iz" csk="0.0000000000" data-stat="pass_int_pct">0.0</td> <td class="right" data-stat="pass_first_down">6</td> <td class="right" csk="0.4666666667" data-stat="pass_success">46.7</td> <td class="right" data-stat="pass_long">71</td> <td class="right" csk="6.0344827586" data-stat="pass_yds_per_att">6.0</td> <td class="right" csk="7.41379310345" data-stat="pass_adj_yds_per_att">7.41</td> <td class="right" csk="10.2941176471" data-stat="pass_yds_per_cmp">10.3</td> <td class="right" csk="43.7500000000" data-stat="pass_yds_per_g">43.8</td> <td class="right" csk="99.1" data-stat="pass_rating">99.1</td> <td class="right" data-stat="pass_sacked">1</td> <td class="right" data-stat="pass_sacked_yds">8</td> <td class="right" csk="0.0333333333" data-stat="pass_sacked_pct">3.33</td> <td class="right" csk="5.5666666667" data-stat="pass_net_yds_per_att">5.57</td> <td class="right" csk="6.90000000000" data-stat="pass_adj_net_yds_per_att">6.90</td> <td class="right iz" data-stat="comebacks">0</td> <td class="right iz" data-stat="gwd">0</td> <td class="left" data-stat="awards"></td> </tr>,
 <tr> <th class="right" csk="3" data-stat="ranker" scope="row">3</th> <td class="left" csk="Saturday Jeff-0" data-append-csv="SatuJe55" data-stat="name_display"><a href="/players/S/SatuJe55.htm">Jeff Saturday</a></td> <td class="right" data-stat="age">29</td> <td class="left" data-stat="pos">C</td> <td class="right" data-stat="games">14</td> <td class="right" data-stat="games_started">14</td> <td class="right" data-stat="qb_rec"></td> <td class="right iz" data-stat="pass_cmp">0</td> <td class="right" data-stat="pass_att">1</td> <td class="right iz" csk="0.0000000000" data-stat="pass_cmp_pct">0.0</td> <td class="right iz" data-stat="pass_yds">0</td> <td class="right iz" data-stat="pass_td">0</td> <td class="right iz" csk="0.0000000000" data-stat="pass_td_pct">0.0</td> <td class="right iz" data-stat="pass_int">0</td> <td class="right iz" csk="0.0000000000" data-stat="pass_int_pct">0.0</td> <td class="right iz" data-stat="pass_first_down">0</td> <td class="right" data-stat="pass_success"></td> <td class="right" data-stat="pass_long"></td> <td class="right iz" csk="0.0000000000" data-stat="pass_yds_per_att">0.0</td> <td class="right iz" csk="0.00000000000" data-stat="pass_adj_yds_per_att">0.00</td> <td class="right" data-stat="pass_yds_per_cmp"></td> <td class="right iz" csk="0.0000000000" data-stat="pass_yds_per_g">0.0</td> <td class="right" csk="39.6" data-stat="pass_rating">39.6</td> <td class="right iz" data-stat="pass_sacked">0</td> <td class="right iz" data-stat="pass_sacked_yds">0</td> <td class="right iz" csk="0.0000000000" data-stat="pass_sacked_pct">0.00</td> <td class="right iz" csk="0.0000000000" data-stat="pass_net_yds_per_att">0.00</td> <td class="right iz" csk="0.00000000000" data-stat="pass_adj_net_yds_per_att">0.00</td> <td class="right iz" data-stat="comebacks">0</td> <td class="right iz" data-stat="gwd">0</td> <td class="left" data-stat="awards"></td> </tr>,
 <tr> <th class="right" data-stat="ranker" scope="row"></th> <td class="left" csk="Manning Peyton" data-stat="name_display">Team Totals</td> <td class="right" data-stat="age"></td> <td class="left" data-stat="pos"></td> <td class="right" data-stat="games">16</td> <td class="right" data-stat="games_started">16</td> <td class="right" csk="0.75000000000" data-stat="qb_rec">12-4-0</td> <td class="right" data-stat="pass_cmp">353</td> <td class="right" data-stat="pass_att">527</td> <td class="right" csk="0.6698292220" data-stat="pass_cmp_pct">67.0</td> <td class="right" data-stat="pass_yds">4623</td> <td class="right" data-stat="pass_td">51</td> <td class="right" csk="0.0967741935" data-stat="pass_td_pct">9.7</td> <td class="right" data-stat="pass_int">10</td> <td class="right" csk="0.0189753321" data-stat="pass_int_pct">1.9</td> <td class="right" data-stat="pass_first_down">239</td> <td class="right" csk="0.5637707948" data-stat="pass_success">56.4</td> <td class="right" data-stat="pass_long">80</td> <td class="right" csk="8.9791271347" data-stat="pass_yds_per_att">9.0</td> <td class="right" csk="10.06072106262" data-stat="pass_adj_yds_per_att">10.06</td> <td class="right" csk="13.4050991501" data-stat="pass_yds_per_cmp">13.4</td> <td class="right" csk="139.1764705882" data-stat="pass_yds_per_g">288.9</td> <td class="right" csk="119.7" data-stat="pass_rating">119.7</td> <td class="right" data-stat="pass_sacked">14</td> <td class="right" data-stat="pass_sacked_yds">109</td> <td class="right" csk="0.0258780037" data-stat="pass_sacked_pct">2.59</td> <td class="right" csk="8.5452865065" data-stat="pass_net_yds_per_att">8.55</td> <td class="right" csk="9.59889094270" data-stat="pass_adj_net_yds_per_att">9.60</td> <td class="right" data-stat="comebacks">2</td> <td class="right" data-stat="gwd">4</td> <td class="left" data-stat="awards"></td> </tr>,

In [27]:
comments = text2.find_all(string=lambda text: isinstance(text, Comment))
tables = []
for c in comments:
    comment_soup = BeautifulSoup(c, "html.parser")
    table = comment_soup.find("table")
    if table:
        tables.append(table)

print(f"Found {len(tables)} hidden tables")
print([t.get("id") for t in tables])  # print their ids

Found 6 hidden tables
['returns', 'kicking', 'punting', 'scoring', 'team_td_log', 'opp_td_log']

In [30]:
#extract all rows and columns for each table
regular = ['passing', 'rushing_and_receiving', 'defense']
overall = ['team_stats', 'games', 'team_conversions']
hidden = tables
all_rows = dict()
all_cols = dict()
for id in table_ids:
    cur = text2.find('table', {'id': id})
    cur_rows= cur.find_all('tr')
    if (id in regular):
        next_id = table_ids[table_ids.index(id) + 1]
        post = text2.find('table', {'id': next_id})
        post_rows = post.find_all('tr')
        all_rows[id] = cur_rows + post_rows
    elif (id in overall):
        all_rows[id] = cur_rows
    else:
        continue
    columnT = cur.find_all('th')
    cols = []
    for title in columnT:
        header = title.get('aria-label')
        cols.append(header)
    all_cols[id] = cols
for table in tables:
    id = table.get("id")
    cur_rows= table.find_all('tr')
    all_rows[id] = cur_rows
        
    columnT = table.find_all('th')
    cols = []
    for title in columnT:
        header = title.get('aria-label')
        cols.append(header)
    all_cols[id] = cols

In [51]:
print(all_cols['team_td_log'])

['Rk', 'Date', ' ', 'Opp', 'Result', 'Quarter', 'Dist', 'Type', 'Detail', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]

In [38]:
for id in all_cols:
    print(id)

team_stats
games
team_conversions
passing
rushing_and_receiving
defense
returns
kicking
punting
scoring
team_td_log
opp_td_log

In [20]:

def find_duplicates(input_list):
    seen = set()
    duplicates = dict()
    for i in range(len(input_list)):
        item = input_list[i]
        if item not in seen:
            seen.add(item)
        else:
            if item in duplicates:
                duplicates[item][0] += 1
                duplicates[item][1].append(i)
            else:
                duplicates[item] = [1,[i]]
    return duplicates

In [59]:
#modify and cleanse columns (remove duplicates)
def modify_cols(all_cols, id):
    cleaned = []
    cols = all_cols.get(id)
    if (id == 'team_stats'):
        cleaned = cols[12:(cols.index("Pts") + 1)]


            

    elif (id == 'games'):
        cleaned = cols[6:(cols.index("Sp. Tms") + 1)]
        
    elif (id == 'passing'):
        cleaned = cols[1:(cols.index("Awards") + 1)]
    elif (id == 'rushing_and_receiving'):
        cleaned = cols[7:(cols.index("Awards") + 1)]
    elif (id == 'team_conversions'):
        cleaned = cols[4:(cols.index("Red Zone Score Pct") + 1)]
    elif (id == 'table_pfr_team-year_game-logs_team-year-regular-season-game-log'
     or id == 'table_pfr_team-year_game-logs_team-year-regular-season-opponent-game-log'):
        cleaned = cols[13:(cols.index("ToP") + 1)]
    elif (id == 'returns'):
        cleaned = cols[5:(cols.index("Awards") + 1)]
    elif (id == 'kicking'):
        cleaned = cols[10:(cols.index("Awards") + 1)]
    elif (id == 'punting'):
        cleaned = cols[4:(cols.index("Awards") + 1)]
    elif (id == 'scoring' or id == 'defense'):
        cleaned = cols[8:(cols.index("Awards") + 1)]
    else:
        cleaned = cols[1:(cols.index("Detail") + 1)]
    
    duplicates = find_duplicates(cleaned)
    for item in duplicates:
        count = duplicates[item][0]
        all_duplicates = duplicates[item][1]
        cur_word = item
        for i in range(count):
            idx = all_duplicates[i]
            cur_word += 'R'
            cleaned[idx] = cur_word
    return cleaned

In [61]:
import os
#get all csvs
for id in all_rows:

    data = []
    rows = all_rows[id]
    cols = all_cols[id]
    for row in rows:
        cols = row.find_all(['td'])
        cols = [col.text.strip() for col in cols]
        data.append(cols)
    cleaned_col_names = modify_cols(all_cols, id)
    df = pd.DataFrame(data, columns=[cleaned_col_names])  # Replace with actual column names
    df = df.drop([0])
    df = df.reset_index(drop=True)
    folder_path = 'Colts statistics page'
    file_name = id + '1.csv'
    path = os.path.join(folder_path, file_name)
    df.to_csv(path, index=False)

In [64]:
#more detailed team and opp game logs
url2 = 'https://www.pro-football-reference.com/teams/clt/2004/gamelog/' 
response2 = requests.get(url2)
print(response2.status_code)

200

In [65]:
text3 = BeautifulSoup(response2.content, 'html.parser')
print(text3.prettify())

<!DOCTYPE html>
<html class="no-js" data-root="/home/pfr/deploy/www" data-version="klecko-" lang="en">
 <head>
  <meta charset="utf-8"/>
  <meta content="ie=edge" http-equiv="x-ua-compatible"/>
  <meta content="width=device-width, initial-scale=1.0, maximum-scale=2.0" name="viewport">
   <link href="https://cdn.ssref.net/req/202508071" rel="dns-prefetch"/>
   <script>
    /* https://docs.osano.com/hc/en-us/articles/22469433444372-Google-Consent-Mode-v2  */
  window.dataLayer = window.dataLayer ||[];
      function gtag(){dataLayer.push(arguments);}
      gtag('consent','default',{
        'ad_storage':'denied',
        'analytics_storage':'denied',
        'ad_user_data':'denied',
        'ad_personalization':'denied',
        'personalization_storage':'denied',
        'functionality_storage':'granted',
        'security_storage':'granted',
        'wait_for_update': 500
      });
      gtag("set", "ads_data_redaction", true);
   </script>
   <script src="https://cmp.osano.com/16CGnCU8UtNhM14sg/12669873-8cf8-41e2-be1f-1cb803cbffe0/osano.js">
   </script>
   <style>
    .osano-cm-widget{display: none;}
   </style>
   <title>
    Indianapolis Colts 2004 Games and Schedule | Pro-Football-Reference.com
   </title>
   <meta content="Indianapolis Colts 2004 Games and Schedule" name="Description"/>
   <link href="https://www.pro-football-reference.com/teams/clt/2004/gamelog" rel="canonical"/>
   <!-- include:start ="/inc/klecko_header_pfr.html_f" -->
   <!-- no:cookie fast load the css.           -->
   <script>
    function gup(n) {n = n.replace(/[\[]/, '\\[').replace(/[\]]/, '\\]'); var r = new RegExp('[\\?&]'+n+'=([^&#]*)'); var re = r.exec(location.search);   return re === null?'':decodeURIComponent(re[1].replace(/\+/g,' '));}; document.srdev = gup('srdev')
   </script>
   <script>
    if (!document.srdev && (location.hostname === 'sup.fb.srdevel.com')) { document.srdev = 'aw'; }/* sf: hardcode this in for sup.fb.srdevel.com for testing purposes. */
   </script>
   <link crossorigin="" href="https://cdn.ssref.net" rel="preconnect"/>
   <link crossorigin="" href="https://www.google-analytics.com" rel="preconnect"/>
   <link crossorigin="" href="https://www.googletagservices.com" rel="preconnect"/>
   <link as="script" crossorigin="" href="https://cdn.ssref.net/req/202508071/js/pfr/sr-min.js" rel="preload"/>
   <link as="fetch" crossorigin="" href="https://cdn.ssref.net/req/202508071/icons/sr_icons-min.svg?pfr" rel="preload"/>
   <link as="fetch" crossorigin="" href="https://www.pro-football-reference.com/short/inc/main_nav_menu.json" rel="preload"/>
   <link as="image" crossorigin="" href="https://cdn.ssref.net/req/201604190/images/chosen-sprite.png" rel="preload"/>
   <link as="style" crossorigin="" href="https://cdn.ssref.net/req/202508071/css/pfr/sr-min.css" rel="preload"/>
   <!-- CSS start -->
   <style>

In [66]:
table_ids2 = [table.get("id") for table in text3.find_all("table") if table.get("id")]
print(table_ids2)

['table_pfr_team-year_game-logs_team-year-regular-season-game-log', 'table_pfr_team-year_game-logs_team-year-playoffs-game-log', 'table_pfr_team-year_game-logs_team-year-regular-season-opponent-game-log', 'table_pfr_team-year_game-logs_team-year-playoffs-opponent-game-log']

In [68]:
all_rows2 = dict()
all_cols2 = dict()
for id in table_ids2:
    cur = text3.find('table', {'id': id})
    cur_rows= cur.find_all('tr')
    if ('playoffs' not in id):
        next_id = table_ids2[table_ids2.index(id) + 1]
        post = text3.find('table', {'id': next_id})
        post_rows = post.find_all('tr')
        all_rows2[id] = cur_rows + post_rows
    else:
        continue
        
    columnT = cur.find_all('th')
    cols = []
    for title in columnT:
        header = title.get('aria-label')
        cols.append(header)
    all_cols2[id] = cols

In [69]:
all_rows.update(all_rows2)
all_cols.update(all_cols2)

In [70]:
import os
#get all csvs
for id in all_rows:

    data = []
    rows = all_rows[id]
    cols = all_cols[id]
    for row in rows:
        cols = row.find_all(['td'])
        cols = [col.text.strip() for col in cols]
        data.append(cols)
    cleaned_col_names = modify_cols(all_cols, id)
    df = pd.DataFrame(data, columns=[cleaned_col_names])  # Replace with actual column names
    df = df.drop([0])
    df = df.reset_index(drop=True)
    folder_path = 'Colts statistics page'
    file_name = id + '1.csv'
    path = os.path.join(folder_path, file_name)
    df.to_csv(path, index=False)

In [29]:
#advanced stats
url3 = 'https://www.pro-football-reference.com/years/2003/index.htm' 
response3 = requests.get(url3)
print(response3.status_code)
text4 = BeautifulSoup(response3.content, 'html.parser')

200

In [30]:
comments = text4.find_all(string=lambda text: isinstance(text, Comment))
tables = []
for c in comments:
    comment_soup = BeautifulSoup(c, "html.parser")
    table = comment_soup.find("table")
    if table:
        tables.append(table)

print(f"Found {len(tables)} hidden tables")
print([t.get("id") for t in tables])  # print their ids

Found 12 hidden tables
['playoff_results', 'afc_playoff_standings', 'nfc_playoff_standings', 'team_stats', 'passing', 'rushing', 'returns', 'kicking', 'punting', 'team_scoring', 'team_conversions', 'drives']

In [31]:
table_ids3 = [table.get("id") for table in tables]
table_ids3

['playoff_results',
 'afc_playoff_standings',
 'nfc_playoff_standings',
 'team_stats',
 'passing',
 'rushing',
 'returns',
 'kicking',
 'punting',
 'team_scoring',
 'team_conversions',
 'drives']

In [36]:
#extract all rows and columns for each table
all_rows3 = dict()
all_cols3 = dict()
for table in tables:
    id = table.get("id")
    cur_rows= table.find_all('tr')
    all_rows3[id] = cur_rows
        
    columnT = table.find_all('th')
    cols = []
    for title in columnT:
        header = title.get('aria-label')
        cols.append(header)
    all_cols3[id] = cols

In [37]:
all_rows3

{'playoff_results': [<tr>
  <th aria-label="Week" class="poptip sort_default_asc sorttable_nosort center" data-stat="week_num" data-tip="Week number in season" scope="col">Week</th>
  <th aria-label="Day" class="poptip sort_default_asc left" data-stat="game_day_of_week" scope="col">Day</th>
  <th aria-label="Date" class="poptip sort_default_asc center" data-stat="game_date" scope="col">Date</th>
  <th aria-label="Winner/tie" class="poptip sort_default_asc center" data-stat="winner" scope="col">Winner/tie</th>
  <th aria-label="" class="poptip sort_default_asc center" data-stat="game_location" scope="col"></th>
  <th aria-label="Loser/tie" class="poptip sort_default_asc center" data-stat="loser" scope="col">Loser/tie</th>
  <th aria-label="" class="poptip sort_default_asc center" data-stat="boxscore_word" scope="col"></th>
  <th aria-label="Pts" class="poptip center" data-stat="pts_win" data-tip="Points Scored by the winning team (first one listed)" scope="col">Pts</th>
  <th aria-label="Pts" class="poptip center" data-stat="pts_lose" data-tip="Points Scored by the losing team (second one listed)" scope="col">Pts</th>
  </tr>,
  <tr><th class="right" csk="31" data-stat="week_num" scope="row">WildCard</th><td class="left" data-stat="game_day_of_week">Sat</td><td class="left" csk="zz1" data-stat="game_date">2004-01-03</td><td class="left" data-stat="winner"><strong><a href="/teams/car/2003.htm">Carolina Panthers</a></strong></td><td class="right iz" data-stat="game_location"></td><td class="left" data-stat="loser"><a href="/teams/dal/2003.htm">Dallas Cowboys</a></td><td class="center" data-stat="boxscore_word"><a href="/boxscores/200401030car.htm">boxscore</a></td><td class="right" data-stat="pts_win"><strong>29</strong></td><td class="right" data-stat="pts_lose">10</td></tr>,
  <tr><th class="right" csk="31" data-stat="week_num" scope="row">WildCard</th><td class="left" data-stat="game_day_of_week">Sat</td><td class="left" csk="zz1" data-stat="game_date">2004-01-03</td><td class="left" data-stat="winner"><strong><a href="/teams/oti/2003.htm">Tennessee Titans</a></strong></td><td class="right" data-stat="game_location">@</td><td class="left" data-stat="loser"><a href="/teams/rav/2003.htm">Baltimore Ravens</a></td><td class="center" data-stat="boxscore_word"><a href="/boxscores/200401030rav.htm">boxscore</a></td><td class="right" data-stat="pts_win"><strong>20</strong></td><td class="right" data-stat="pts_lose">17</td></tr>,
  <tr><th class="right" csk="31" data-stat="week_num" scope="row">WildCard</th><td class="left" data-stat="game_day_of_week">Sun</td><td class="left" csk="zz1" data-stat="game_date">2004-01-04</td><td class="left" data-stat="winner"><strong><a href="/teams/clt/2003.htm">Indianapolis Colts</a></strong></td><td class="right iz" data-stat="game_location"></td><td class="left" data-stat="loser"><a href="/teams/den/2003.htm">Denver Broncos</a></td><td class="center" data-stat="boxscore_word"><a href="/boxscores/200401040clt.htm">boxscore</a></td><td class="right" data-stat="pts_win"><strong>41</strong></td><td class="right" data-stat="pts_lose">10</td></tr>,
  <tr><th class="right" csk="31" data-stat="week_num" scope="row">WildCard</th><td class="left" data-stat="game_day_of_week">Sun</td><td class="left" csk="zz1" data-stat="game_date">2004-01-04</td><td class="left" data-stat="winner"><strong><a href="/teams/gnb/2003.htm">Green Bay Packers</a></strong></td><td class="right iz" data-stat="game_location"></td><td class="left" data-stat="loser"><a href="/teams/sea/2003.htm">Seattle Seahawks</a></td><td class="center" data-stat="boxscore_word"><a href="/boxscores/200401040gnb.htm">boxscore</a></td><td class="right" data-stat="pts_win"><strong>33</strong></td><td class="right" data-stat="pts_lose">27</td></tr>,
  <tr><th class="right" csk="32" data-stat="week_num" scope="row">Division</th><td class="left" data-stat="game_day_of_week">Sat</td><td class="left" csk="zz3" data-stat="game_date">2004-01-10</td><td class="left" data-stat="winner"><strong><a href="/teams/nwe/2003.htm">New England Patriots</a></strong></td><td class="right iz" data-stat="game_location"></td><td class="left" data-stat="loser"><a href="/teams/oti/2003.htm">Tennessee Titans</a></td><td class="center" data-stat="boxscore_word"><a href="/boxscores/200401100nwe.htm">boxscore</a></td><td class="right" data-stat="pts_win"><strong>17</strong></td><td class="right" data-stat="pts_lose">14</td></tr>,
  <tr><th class="right" csk="32" data-stat="week_num" scope="row">Division</th><td class="left" data-stat="game_day_of_week">Sat</td><td class="left" csk="zz3" data-stat="game_date">2004-01-10</td><td class="left" data-stat="winner"><strong><a href="/teams/car/2003.htm">Carolina Panthers</a></strong></td><td class="right" data-stat="game_location">@</td><td class="left" data-stat="loser"><a href="/teams/ram/2003.htm">St. Louis Rams</a></td><td class="center" data-stat="boxscore_word"><a href="/boxscores/200401100ram.htm">boxscore</a></td><td class="right" data-stat="pts_win"><strong>29</strong></td><td class="right" data-stat="pts_lose">23</td></tr>,
  <tr><th class="right" csk="32" data-stat="week_num" scope="row">Division</th><td class="left" data-stat="game_day_of_week">Sun</td><td class="left" csk="zz3" data-stat="game_date">2004-01-11</td><td class="left" data-stat="winner"><strong><a href="/teams/phi/2003.htm">Philadelphia Eagles</a></strong></td><td class="right iz" data-stat="game_location"></td><td class="left" data-stat="loser"><a href="/teams/gnb/2003.htm">Green Bay Packers</a></td><td class="center" data-stat="boxscore_word"><a href="/boxscores/200401110phi.htm">boxscore</a></td><td class="right" data-stat="pts_win"><strong>20</strong></td><td class="right" data-stat="pts_lose">17</td></tr>,
  <tr><th class="right" csk="32" data-stat="week_num" scope="row">Division</th><td class="left" data-stat="game_day_of_week">Sun</td><td class="left" csk="zz3" data-stat="game_date">2004-01-11</td><td class="left" data-stat="winner"><strong><a href="/teams/clt/2003.htm">Indianapolis Colts</a></strong></td><td class="right" data-stat="game_location">@</td><td class="left" data-stat="loser"><a href="/teams/kan/2003.htm">Kansas City Chiefs</a></td><td class="center" data-stat="boxscore_word"><a href="/boxscores/200401110kan.htm">boxscore</a></td><td class="right" data-stat="pts_win"><strong>38</strong></td><td class="right" data-stat="pts_lose">31</td></tr>,
  <tr><th class="right" csk="33" data-stat="week_num" scope="row">ConfChamp</th><td class="left" data-stat="game_day_of_week">Sun</td><td class="left" csk="zz5" data-stat="game_date">2004-01-18</td><td class="left" data-stat="winner"><strong><a href="/teams/nwe/2003.htm">New England Patriots</a></strong></td><td class="right iz" data-stat="game_location"></td><td class="left" data-stat="loser"><a href="/teams/clt/2003.htm">Indianapolis Colts</a></td><td class="center" data-stat="boxscore_word"><a href="/boxscores/200401180nwe.htm">boxscore</a></td><td class="right" data-stat="pts_win"><strong>24</strong></td><td class="right" data-stat="pts_lose">14</td></tr>,
  <tr><th class="right" csk="33" data-stat="week_num" scope="row">ConfChamp</th><td class="left" data-stat="game_day_of_week">Sun</td><td class="left" csk="zz5" data-stat="game_date">2004-01-18</td><td class="left" data-stat="winner"><strong><a href="/teams/car/2003.htm">Carolina Panthers</a></strong></td><td class="right" data-stat="game_location">@</td><td class="left" data-stat="loser"><a href="/teams/phi/2003.htm">Philadelphia Eagles</a></td><td class="center" data-stat="boxscore_word"><a href="/boxscores/200401180phi.htm">boxscore</a></td><td class="right" data-stat="pts_win"><strong>14</strong></td><td class="right" data-stat="pts_lose">3</td></tr>,
  <tr><th class="right" csk="34" data-stat="week_num" scope="row">SuperBowl</th><td class="left" data-stat="game_day_of_week">Sun</td><td class="left" csk="zz8" data-stat="game_date">2004-02-01</td><td class="left" data-stat="winner"><strong><a href="/teams/nwe/2003.htm">New England Patriots</a></strong></td><td class="right" data-stat="game_location">N</td><td class="left" data-stat="loser"><a href="/teams/car/2003.htm">Carolina Panthers</a></td><td class="center" data-stat="boxscore_word"><a href="/boxscores/200402010car.htm">boxscore</a></td><td class="right" data-stat="pts_win"><strong>32</strong></td><td class="right" data-stat="pts_lose">29</td></tr>],
 'afc_playoff_standings': [<tr>
  <th aria-label="Tm" class="poptip sort_default_asc show_partial_when_sorting left" data-stat="team" scope="col">Tm</th>
  <th aria-label="Wins" class="poptip center" data-stat="wins" data-tip="Games Won" scope="col">W</th>
  <th aria-label="Losses" class="poptip center" data-stat="losses" data-tip="Games Lost" scope="col">L</th>
  <th aria-label="Ties" class="poptip center" data-stat="ties" data-tip="Tie Games" scope="col">T</th>
  <th aria-label="Position" class="poptip center" data-stat="why" scope="col">Position</th>
  <th aria-label="Reason" class="poptip center" data-stat="reason" data-tip="Reason the team is seeded the way it is, based on NFL tiebreaker rules" scope="col">Reason</th>
  </tr>,
  <tr><th class="left" csk="1" data-stat="team" scope="row"><a href="/teams/nwe/2003.htm"><a href="/teams/nwe/2003.htm">New England Patriots</a> (1)</a></th><td class="right" data-stat="wins">14</td><td class="right" data-stat="losses">2</td><td class="right iz" data-stat="ties">0</td><td class="right" data-stat="why">East Champion</td><td class="right iz" data-stat="reason"></td></tr>,
  <tr><th class="left" csk="2" data-stat="team" scope="row"><a href="/teams/kan/2003.htm"><a href="/teams/kan/2003.htm">Kansas City Chiefs</a> (2)</a></th><td class="right" data-stat="wins">13</td><td class="right" data-stat="losses">3</td><td class="right iz" data-stat="ties">0</td><td class="right" data-stat="why">West Champion</td><td class="right iz" data-stat="reason"></td></tr>,
  <tr><th class="left" csk="3" data-stat="team" scope="row"><a href="/teams/clt/2003.htm"><a href="/teams/clt/2003.htm">Indianapolis Colts</a> (3)</a></th><td class="right" data-stat="wins">12</td><td class="right" data-stat="losses">4</td><td class="right iz" data-stat="ties">0</td><td class="right" data-stat="why">South Champion</td><td class="right" data-stat="reason">head-to-head record</td></tr>,
  <tr><th class="left" csk="4" data-stat="team" scope="row"><a href="/teams/rav/2003.htm"><a href="/teams/rav/2003.htm">Baltimore Ravens</a> (4)</a></th><td class="right" data-stat="wins">10</td><td class="right" data-stat="losses">6</td><td class="right iz" data-stat="ties">0</td><td class="right" data-stat="why">North Champion</td><td class="right iz" data-stat="reason"></td></tr>,
  <tr><th class="left" csk="5" data-stat="team" scope="row"><a href="/teams/oti/2003.htm"><a href="/teams/oti/2003.htm">Tennessee Titans</a> (5)</a></th><td class="right" data-stat="wins">12</td><td class="right" data-stat="losses">4</td><td class="right iz" data-stat="ties">0</td><td class="right" data-stat="why">Wild Card #1</td><td class="right iz" data-stat="reason"></td></tr>,
  <tr><th class="left" csk="6" data-stat="team" scope="row"><a href="/teams/den/2003.htm"><a href="/teams/den/2003.htm">Denver Broncos</a> (6)</a></th><td class="right" data-stat="wins">10</td><td class="right" data-stat="losses">6</td><td class="right iz" data-stat="ties">0</td><td class="right" data-stat="why">Wild Card #2</td><td class="right" data-stat="reason">conference win percentage</td></tr>,
  <tr class="divider"><th class="left" csk="7" data-stat="team" scope="row"><a href="/teams/mia/2003.htm"><a href="/teams/mia/2003.htm">Miami Dolphins</a></a></th><td class="right" data-stat="wins">10</td><td class="right" data-stat="losses">6</td><td class="right iz" data-stat="ties">0</td><td class="right iz" data-stat="why"></td><td class="right iz" data-stat="reason"></td></tr>,
  <tr><th class="left" csk="8" data-stat="team" scope="row"><a href="/teams/cin/2003.htm"><a href="/teams/cin/2003.htm">Cincinnati Bengals</a></a></th><td class="right" data-stat="wins">8</td><td class="right" data-stat="losses">8</td><td class="right iz" data-stat="ties">0</td><td class="right iz" data-stat="why"></td><td class="right iz" data-stat="reason"></td></tr>,
  <tr><th class="left" csk="9" data-stat="team" scope="row"><a href="/teams/pit/2003.htm"><a href="/teams/pit/2003.htm">Pittsburgh Steelers</a></a></th><td class="right" data-stat="wins">6</td><td class="right" data-stat="losses">10</td><td class="right iz" data-stat="ties">0</td><td class="right iz" data-stat="why"></td><td class="right" data-stat="reason">conference win percentage</td></tr>,
  <tr><th class="left" csk="10" data-stat="team" scope="row"><a href="/teams/buf/2003.htm"><a href="/teams/buf/2003.htm">Buffalo Bills</a></a></th><td class="right" data-stat="wins">6</td><td class="right" data-stat="losses">10</td><td class="right iz" data-stat="ties">0</td><td class="right iz" data-stat="why"></td><td class="right" data-stat="reason">division win percentage</td></tr>,
  <tr><th class="left" csk="11" data-stat="team" scope="row"><a href="/teams/nyj/2003.htm"><a href="/teams/nyj/2003.htm">New York Jets</a></a></th><td class="right" data-stat="wins">6</td><td class="right" data-stat="losses">10</td><td class="right iz" data-stat="ties">0</td><td class="right iz" data-stat="why"></td><td class="right iz" data-stat="reason"></td></tr>,
  <tr><th class="left" csk="12" data-stat="team" scope="row"><a href="/teams/jax/2003.htm"><a href="/teams/jax/2003.htm">Jacksonville Jaguars</a></a></th><td class="right" data-stat="wins">5</td><td class="right" data-stat="losses">11</td><td class="right iz" data-stat="ties">0</td><td class="right iz" data-stat="why"></td><td class="right" data-stat="reason">win percentage in common games</td></tr>,
  <tr><th class="left" csk="13" data-stat="team" scope="row"><a href="/teams/cle/2003.htm"><a href="/teams/cle/2003.htm">Cleveland Browns</a></a></th><td class="right" data-stat="wins">5</td><td class="right" data-stat="losses">11</td><td class="right iz" data-stat="ties">0</td><td class="right iz" data-stat="why"></td><td class="right" data-stat="reason">win percentage in common games</td></tr>,
  <tr><th class="left" csk="14" data-stat="team" scope="row"><a href="/teams/htx/2003.htm"><a href="/teams/htx/2003.htm">Houston Texans</a></a></th><td class="right" data-stat="wins">5</td><td class="right" data-stat="losses">11</td><td class="right iz" data-stat="ties">0</td><td class="right iz" data-stat="why"></td><td class="right iz" data-stat="reason"></td></tr>,
  <tr><th class="left" csk="15" data-stat="team" scope="row"><a href="/teams/rai/2003.htm"><a href="/teams/rai/2003.htm">Oakland Raiders</a></a></th><td class="right" data-stat="wins">4</td><td class="right" data-stat="losses">12</td><td class="right iz" data-stat="ties">0</td><td class="right iz" data-stat="why"></td><td class="right" data-stat="reason">conference win percentage</td></tr>,
  <tr><th class="left" csk="16" data-stat="team" scope="row"><a href="/teams/sdg/2003.htm"><a href="/teams/sdg/2003.htm">San Diego Chargers</a></a></th><td class="right" data-stat="wins">4</td><td class="right" data-stat="losses">12</td><td class="right iz" data-stat="ties">0</td><td class="right iz" data-stat="why"></td><td class="right iz" data-stat="reason"></td></tr>],
 'nfc_playoff_standings': [<tr>
  <th aria-label="Tm" class="poptip sort_default_asc show_partial_when_sorting left" data-stat="team" scope="col">Tm</th>
  <th aria-label="Wins" class="poptip center" data-stat="wins" data-tip="Games Won" scope="col">W</th>
  <th aria-label="Losses" class="poptip center" data-stat="losses" data-tip="Games Lost" scope="col">L</th>
  <th aria-label="Ties" class="poptip center" data-stat="ties" data-tip="Tie Games" scope="col">T</th>
  <th aria-label="Position" class="poptip center" data-stat="why" scope="col">Position</th>
  <th aria-label="Reason" class="poptip center" data-stat="reason" data-tip="Reason the team is seeded the way it is, based on NFL tiebreaker rules" scope="col">Reason</th>
  </tr>,
  <tr><th class="left" csk="1" data-stat="team" scope="row"><a href="/teams/phi/2003.htm"><a href="/teams/phi/2003.htm">Philadelphia Eagles</a> (1)</a></th><td class="right" data-stat="wins">12</td><td class="right" data-stat="losses">4</td><td class="right iz" data-stat="ties">0</td><td class="right" data-stat="why">East Champion</td><td class="right" data-stat="reason">conference win percentage</td></tr>,
  <tr><th class="left" csk="2" data-stat="team" scope="row"><a href="/teams/ram/2003.htm"><a href="/teams/ram/2003.htm">St. Louis Rams</a> (2)</a></th><td class="right" data-stat="wins">12</td><td class="right" data-stat="losses">4</td><td class="right iz" data-stat="ties">0</td><td class="right" data-stat="why">West Champion</td><td class="right iz" data-stat="reason"></td></tr>,
  <tr><th class="left" csk="3" data-stat="team" scope="row"><a href="/teams/car/2003.htm"><a href="/teams/car/2003.htm">Carolina Panthers</a> (3)</a></th><td class="right" data-stat="wins">11</td><td class="right" data-stat="losses">5</td><td class="right iz" data-stat="ties">0</td><td class="right" data-stat="why">South Champion</td><td class="right iz" data-stat="reason"></td></tr>,
  <tr><th class="left" csk="4" data-stat="team" scope="row"><a href="/teams/gnb/2003.htm"><a href="/teams/gnb/2003.htm">Green Bay Packers</a> (4)</a></th><td class="right" data-stat="wins">10</td><td class="right" data-stat="losses">6</td><td class="right iz" data-stat="ties">0</td><td class="right" data-stat="why">North Champion</td><td class="right iz" data-stat="reason"></td></tr>,
  <tr><th class="left" csk="5" data-stat="team" scope="row"><a href="/teams/sea/2003.htm"><a href="/teams/sea/2003.htm">Seattle Seahawks</a> (5)</a></th><td class="right" data-stat="wins">10</td><td class="right" data-stat="losses">6</td><td class="right iz" data-stat="ties">0</td><td class="right" data-stat="why">Wild Card #1</td><td class="right" data-stat="reason">strength of victory</td></tr>,
  <tr><th class="left" csk="6" data-stat="team" scope="row"><a href="/teams/dal/2003.htm"><a href="/teams/dal/2003.htm">Dallas Cowboys</a> (6)</a></th><td class="right" data-stat="wins">10</td><td class="right" data-stat="losses">6</td><td class="right iz" data-stat="ties">0</td><td class="right" data-stat="why">Wild Card #2</td><td class="right iz" data-stat="reason"></td></tr>,
  <tr class="divider"><th class="left" csk="7" data-stat="team" scope="row"><a href="/teams/min/2003.htm"><a href="/teams/min/2003.htm">Minnesota Vikings</a></a></th><td class="right" data-stat="wins">9</td><td class="right" data-stat="losses">7</td><td class="right iz" data-stat="ties">0</td><td class="right iz" data-stat="why"></td><td class="right iz" data-stat="reason"></td></tr>,
  <tr><th class="left" csk="8" data-stat="team" scope="row"><a href="/teams/nor/2003.htm"><a href="/teams/nor/2003.htm">New Orleans Saints</a></a></th><td class="right" data-stat="wins">8</td><td class="right" data-stat="losses">8</td><td class="right iz" data-stat="ties">0</td><td class="right iz" data-stat="why"></td><td class="right iz" data-stat="reason"></td></tr>,
  <tr><th class="left" csk="9" data-stat="team" scope="row"><a href="/teams/sfo/2003.htm"><a href="/teams/sfo/2003.htm">San Francisco 49ers</a></a></th><td class="right" data-stat="wins">7</td><td class="right" data-stat="losses">9</td><td class="right iz" data-stat="ties">0</td><td class="right iz" data-stat="why"></td><td class="right" data-stat="reason">head-to-head record</td></tr>,

In [44]:
print(table_ids3)

['playoff_results', 'afc_playoff_standings', 'nfc_playoff_standings', 'team_stats', 'passing', 'rushing', 'returns', 'kicking', 'punting', 'team_scoring', 'team_conversions', 'drives']

In [50]:
for id in all_cols3:
    print(all_cols3[id])

['Week', 'Day', 'Date', 'Winner/tie', '', 'Loser/tie', '', 'Pts', 'Pts', None, None, None, None, None, None, None, None, None, None, None]
['Tm', 'Wins', 'Losses', 'Ties', 'Position', 'Reason', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['Tm', 'Wins', 'Losses', 'Ties', 'Position', 'Reason', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', None, None, None, '', None, None, '', '', '', '', None, 'Rk', 'Tm', 'Games', 'Points For', 'Yds', ' Offensive Plays Run ', ' Yards Per Offensive Play ', 'Turnovers', 'Fumbles Lost', '1st Downs', 'Passes Completed', 'Pass Attempts', 'Passing Yds', 'Passing TD', 'Passes Intercepted', 'Net Yds/Pass Att', '1stD', 'Rushing Att', 'Rushing Yds', 'Rushing TD', 'Yds/Rushing Att', '1stD', 'Penalties', 'Penalty Yds', '1stPy', 'Sc%', 'TO%', 'EXP', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['Rk', 'Tm', 'Games', 'Passes Completed', 'Pass Attempts', 'Pass Completion %', 'Passing Yds', 'Passing TD', 'Passing TD %', 'Passes Intercepted', 'Pass Intercept. %', 'Long Pass', 'Yds/Pass Att', 'Adj Yds/Pass Att', 'Yds/Pass Cmp', 'Passing Yds/Game', 'Passer Rating', 'Sacked ', 'Sacked Yds Lost', 'Sack %', 'Net Yds/Pass Att', 'Adj Net Yds/Pass Att', 'Comebacks', 'Game-Winning Drives', 'EXP', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['Rk', 'Tm', 'Games', 'Rushing Att', 'Rushing Yds', 'Rushing TD', 'Long Rush', 'Yds/Rushing Att', 'Rushing Yds/Game', 'Fumbles', 'EXP', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', None, '', '', None, 'Rk', 'Tm', 'Games', 'Punt Returns', 'Punt Return Yds', 'Punt Return TD', 'Long Punt Return', 'Yds/Punt Return', 'Kick Returns', 'Kick Return Yds', 'Kick Return TD', 'Long Kick Return', 'Yds/Kick Return', 'All-Purpose Yds', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', None, '', '', '', '', '', '', '', 'Rk', 'Tm', 'Games', 'Field Goals Attempted, 19 yards and under', 'Field Goals Made, 19 yards and under', 'Field Goals Attempted, 20-29 yards', 'Field Goals Made, 20-29 yards', 'Field Goals Attempted, 30-39 yards', 'Field Goals Made, 30-39 yards', 'Field Goals Attempted, 40-49 yards', 'Field Goals Made, 40-49 yards', 'Field Goals Attempted, 50+ yards', 'Field Goals Made, 50+ yards', 'Field Goals Att', 'Field Goals Made', 'Long FGM', 'Field Goal %', 'Extra Pt Att', 'Extra Pt Made', 'Extra Point %', 'Kickoffs', 'Kickoff Yards', 'Kickoff touchbacks', 'Touchback Percentage', 'Avg. Kickoff Yards', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', None, '', 'Rk', 'Tm', 'Games', 'Punts', 'Punting Yds', 'Yds/Punt', 'opp Punt Return Yds', 'Punt Net Yds', 'Punt Net Yds/Punt', 'Long Punt', 'Punt TB', 'Punt Touchback %', 'Punt In 20', 'Punt In 20 %', 'Punts Blocked', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['Rk', 'Tm', 'Games', 'RshTD', 'RecTD', 'PR TD', 'KR TD', 'FblTD', 'IntTD', 'OthTD', 'AllTD', '2-pt. Conv. Made', '2-pt. Conv. Att', 'Def 2-pt. Conv.', 'Extra Pt Made', 'Extra Pt Att', 'Field Goals Made', 'Field Goals Att', 'Safeties', 'Points Scored', 'Pts/G', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', None, '', '', 'Rk', 'Tm', 'Games', '3rd Down Attempts', '3rd Down Conversions', '3rd Down Conv Pct', '4th Down Attempts', '4th Down Conversions', '4th Down Conv Pct', 'Red Zone Attempts', 'Red Zone TD', 'Red Zone Score Pct', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', None, '', '', 'Rk', 'Tm', 'Games', '#Dr', 'Plays', 'Sc%', 'TO%', 'Plays', 'Yds', 'Start', 'Time', 'Pts', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]

In [71]:
#modify and cleanse columns (remove duplicates)
def modify_cols2(all_cols, id):
    cleaned = []
    cols = all_cols.get(id)
    if (id == 'playoff_results'):
        cleaned = cols[0:9]
    
    elif (id == 'AFC' or id == 'NFC'):
        cleaned = cols[1:(cols.index("DSRS") + 1)]

    elif (id == 'afc_playoff_standings' or id == 'nfc_playoff_standings'):
        cleaned = cols[1:(cols.index("Reason") + 1)]
        
    elif (id == 'team_stats'):
        cleaned = cols[13:(cols.index("EXP") + 1)]
    elif (id == 'passing' or id == 'rushing'):
        cleaned = cols[1:(cols.index("EXP") + 1)]
    elif (id == 'returns'):
        cleaned = cols[6:(cols.index("All-Purpose Yds") + 1)]
    elif (id == 'kicking'):
        cleaned = cols[10:(cols.index("Avg. Kickoff Yards") + 1)]
    elif (id == 'punting'):
        cleaned = cols[4:(cols.index("Punts Blocked") + 1)]
    elif (id == 'team_scoring'):
        cleaned = cols[1:(cols.index("Pts/G") + 1)]
    elif (id == 'team_conversions'):
        cleaned = cols[5:(cols.index("Red Zone Score Pct") + 1)]
    else:
        cleaned = cols[5:(cols.index("Pts") + 1)]
    
    duplicates = find_duplicates(cleaned)
    for item in duplicates:
        count = duplicates[item][0]
        all_duplicates = duplicates[item][1]
        cur_word = item
        for i in range(count):
            idx = all_duplicates[i]
            cur_word += 'R'
            cleaned[idx] = cur_word
    return cleaned

In [79]:
#for all advanced stats
for id in all_rows3:

    data = []
    rows = all_rows3[id]
    cols = all_cols3[id]
    for row in rows:
        cols = row.find_all(['td', 'th'])
        cols = [col.text.strip() for col in cols]
        data.append(cols)
    cleaned_col_names = modify_cols2(all_cols3, id)
    df = pd.DataFrame(data, columns=[cleaned_col_names])  # Replace with actual column names
    df = df.drop([0, 1])
    df.to_csv(id + '1.csv', index=False)

In [66]:
#afc and nfc standings
standings= [table.get("id") for table in text4.find_all("table") if table.get("id")]
print(standings)

['AFC', 'NFC']

In [68]:
for id in standings:
    table = text4.find('table', {'id': id})
    rows = table.find_all('tr')
    all_rows3[id] = rows
    columnT = table.find_all('th')
    cols = []
    for title in columnT:
        header = title.get('aria-label')
        cols.append(header)
    all_cols3[id] = cols

In [73]:
all_cols3["playoff_results"]

['Week',
 'Day',
 'Date',
 'Winner/tie',
 '',
 'Loser/tie',
 '',
 'Pts',
 'Pts',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [70]:
all_cols3["NFC"]

['Tm',
 'Wins',
 'Losses',
 'W-L%',
 'Points For',
 'Points Allowed',
 'Points Differential',
 'MoV',
 'SoS',
 'SRS',
 'OSRS',
 'DSRS',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [74]:
all_rows3["AFC"]

[<tr>
 <th aria-label="Tm" class="poptip sort_default_asc show_partial_when_sorting left" data-stat="team" scope="col">Tm</th>
 <th aria-label="Wins" class="poptip center" data-stat="wins" data-tip="Games Won" scope="col">W</th>
 <th aria-label="Losses" class="poptip center" data-stat="losses" data-tip="Games Lost" scope="col">L</th>
 <th aria-label="W-L%" class="poptip hide_non_quals center" data-stat="win_loss_perc" data-tip="&lt;b&gt;Win-Loss Percentage of team&lt;/b&gt;&lt;br&gt;For coaches, minimum to qualify for leading is 50 games.&lt;br&gt;After 1972, ties are counted as half-wins and half-losses.&lt;br&gt;Prior, the league didn\'t count them as games in W-L% calculations." scope="col">W-L%</th>
 <th aria-label="Points For" class="poptip center" data-stat="points" data-tip="Points Scored by team" scope="col">PF</th>
 <th aria-label="Points Allowed" class="poptip center" data-stat="points_opp" data-tip="Points Scored by opposition" scope="col">PA</th>
 <th aria-label="Points Differential" class="poptip center" data-stat="points_diff" data-tip="&lt;b&gt;Points Differential&lt;/b&gt;&lt;br&gt;Points Scored - Points Allowed" scope="col">PD</th>
 <th aria-label="MoV" class="poptip center" data-stat="mov" data-tip="&lt;b&gt;Margin of Victory&lt;/b&gt;&lt;br&gt;(Points Scored - Points Allowed)/ Games Played" scope="col">MoV</th>
 <th aria-label="SoS" class="poptip center" data-stat="sos_total" data-tip="&lt;b&gt;Strength of Schedule&lt;/b&gt;&lt;br&gt;Average quality of opponent as measured by SRS (Simple Rating System)" scope="col">SoS</th>
 <th aria-label="SRS" class="poptip center" data-stat="srs_total" data-tip="&lt;b&gt;Simple Rating System&lt;/b&gt;&lt;br&gt;Team quality relative to average (0.0) as measured by SRS (Simple Rating System)&lt;br&gt;SRS = MoV + SoS = OSRS + DSRS&lt;br&gt;The difference in SRS can be considered a point spread (add about 2 pt for HFA)" scope="col">SRS</th>
 <th aria-label="OSRS" class="poptip center" data-stat="srs_offense" data-tip="&lt;b&gt;Offensive SRS&lt;/b&gt;&lt;br&gt;Team offense quality relative to average (0.0) as measured by SRS (Simple Rating System)" scope="col">OSRS</th>
 <th aria-label="DSRS" class="poptip center" data-stat="srs_defense" data-tip="&lt;b&gt;Defensive SRS&lt;/b&gt;&lt;br&gt;Team defense quality relative to average (0.0) as measured by SRS (Simple Rating System)" scope="col">DSRS</th>
 </tr>,
 <tr class="thead onecell"><td class="right left" colspan="12" data-stat="onecell"> AFC East</td></tr>,
 <tr><th class="left" csk="1" data-stat="team" scope="row"><a href="/teams/nwe/2003.htm">New England Patriots</a>*</th><td class="right" data-stat="wins">14</td><td class="right" data-stat="losses">2</td><td class="right" data-stat="win_loss_perc">.875</td><td class="right" data-stat="points">348</td><td class="right" data-stat="points_opp">238</td><td class="right" data-stat="points_diff">110</td><td class="right" data-stat="mov">6.9</td><td class="right" data-stat="sos_total">0.1</td><td class="right" data-stat="srs_total">6.9</td><td class="right" data-stat="srs_offense">2.1</td><td class="right" data-stat="srs_defense">4.9</td></tr>,
 <tr><th class="left" csk="2" data-stat="team" scope="row"><a href="/teams/mia/2003.htm">Miami Dolphins</a></th><td class="right" data-stat="wins">10</td><td class="right" data-stat="losses">6</td><td class="right" data-stat="win_loss_perc">.625</td><td class="right" data-stat="points">311</td><td class="right" data-stat="points_opp">261</td><td class="right" data-stat="points_diff">50</td><td class="right" data-stat="mov">3.1</td><td class="right" data-stat="sos_total">0.3</td><td class="right" data-stat="srs_total">3.4</td><td class="right" data-stat="srs_offense">-0.7</td><td class="right" data-stat="srs_defense">4.1</td></tr>,
 <tr><th class="left" csk="3" data-stat="team" scope="row"><a href="/teams/buf/2003.htm">Buffalo Bills</a></th><td class="right" data-stat="wins">6</td><td class="right" data-stat="losses">10</td><td class="right" data-stat="win_loss_perc">.375</td><td class="right" data-stat="points">243</td><td class="right" data-stat="points_opp">279</td><td class="right" data-stat="points_diff">-36</td><td class="right" data-stat="mov">-2.3</td><td class="right" data-stat="sos_total">1.3</td><td class="right" data-stat="srs_total">-1.0</td><td class="right" data-stat="srs_offense">-5.0</td><td class="right" data-stat="srs_defense">4.0</td></tr>,
 <tr><th class="left" csk="4" data-stat="team" scope="row"><a href="/teams/nyj/2003.htm">New York Jets</a></th><td class="right" data-stat="wins">6</td><td class="right" data-stat="losses">10</td><td class="right" data-stat="win_loss_perc">.375</td><td class="right" data-stat="points">283</td><td class="right" data-stat="points_opp">299</td><td class="right" data-stat="points_diff">-16</td><td class="right" data-stat="mov">-1.0</td><td class="right" data-stat="sos_total">0.4</td><td class="right" data-stat="srs_total">-0.6</td><td class="right" data-stat="srs_offense">-1.9</td><td class="right" data-stat="srs_defense">1.3</td></tr>,
 <tr class="thead onecell"><td class="right left" colspan="12" data-stat="onecell"> AFC North</td></tr>,
 <tr><th class="left" csk="6" data-stat="team" scope="row"><a href="/teams/rav/2003.htm">Baltimore Ravens</a>*</th><td class="right" data-stat="wins">10</td><td class="right" data-stat="losses">6</td><td class="right" data-stat="win_loss_perc">.625</td><td class="right" data-stat="points">391</td><td class="right" data-stat="points_opp">281</td><td class="right" data-stat="points_diff">110</td><td class="right" data-stat="mov">6.9</td><td class="right" data-stat="sos_total">-0.6</td><td class="right" data-stat="srs_total">6.3</td><td class="right" data-stat="srs_offense">3.3</td><td class="right" data-stat="srs_defense">3.0</td></tr>,
 <tr><th class="left" csk="7" data-stat="team" scope="row"><a href="/teams/cin/2003.htm">Cincinnati Bengals</a></th><td class="right" data-stat="wins">8</td><td class="right" data-stat="losses">8</td><td class="right" data-stat="win_loss_perc">.500</td><td class="right" data-stat="points">346</td><td class="right" data-stat="points_opp">384</td><td class="right" data-stat="points_diff">-38</td><td class="right" data-stat="mov">-2.4</td><td class="right iz" data-stat="sos_total">0.0</td><td class="right" data-stat="srs_total">-2.4</td><td class="right" data-stat="srs_offense">1.1</td><td class="right" data-stat="srs_defense">-3.5</td></tr>,
 <tr><th class="left" csk="8" data-stat="team" scope="row"><a href="/teams/pit/2003.htm">Pittsburgh Steelers</a></th><td class="right" data-stat="wins">6</td><td class="right" data-stat="losses">10</td><td class="right" data-stat="win_loss_perc">.375</td><td class="right" data-stat="points">300</td><td class="right" data-stat="points_opp">327</td><td class="right" data-stat="points_diff">-27</td><td class="right" data-stat="mov">-1.7</td><td class="right" data-stat="sos_total">0.6</td><td class="right" data-stat="srs_total">-1.1</td><td class="right" data-stat="srs_offense">-2.5</td><td class="right" data-stat="srs_defense">1.4</td></tr>,
 <tr><th class="left" csk="9" data-stat="team" scope="row"><a href="/teams/cle/2003.htm">Cleveland Browns</a></th><td class="right" data-stat="wins">5</td><td class="right" data-stat="losses">11</td><td class="right" data-stat="win_loss_perc">.313</td><td class="right" data-stat="points">254</td><td class="right" data-stat="points_opp">322</td><td class="right" data-stat="points_diff">-68</td><td class="right" data-stat="mov">-4.3</td><td class="right" data-stat="sos_total">1.3</td><td class="right" data-stat="srs_total">-2.9</td><td class="right" data-stat="srs_offense">-5.3</td><td class="right" data-stat="srs_defense">2.4</td></tr>,
 <tr class="thead onecell"><td class="right left" colspan="12" data-stat="onecell"> AFC South</td></tr>,
 <tr><th class="left" csk="11" data-stat="team" scope="row"><a href="/teams/clt/2003.htm">Indianapolis Colts</a>*</th><td class="right" data-stat="wins">12</td><td class="right" data-stat="losses">4</td><td class="right" data-stat="win_loss_perc">.750</td><td class="right" data-stat="points">447</td><td class="right" data-stat="points_opp">336</td><td class="right" data-stat="points_diff">111</td><td class="right" data-stat="mov">6.9</td><td class="right iz" data-stat="sos_total">0.0</td><td class="right" data-stat="srs_total">7.0</td><td class="right" data-stat="srs_offense">8.2</td><td class="right" data-stat="srs_defense">-1.2</td></tr>,
 <tr><th class="left" csk="12" data-stat="team" scope="row"><a href="/teams/oti/2003.htm">Tennessee Titans</a>+</th><td class="right" data-stat="wins">12</td><td class="right" data-stat="losses">4</td><td class="right" data-stat="win_loss_perc">.750</td><td class="right" data-stat="points">435</td><td class="right" data-stat="points_opp">324</td><td class="right" data-stat="points_diff">111</td><td class="right" data-stat="mov">6.9</td><td class="right" data-stat="sos_total">-0.5</td><td class="right" data-stat="srs_total">6.5</td><td class="right" data-stat="srs_offense">7.0</td><td class="right" data-stat="srs_defense">-0.5</td></tr>,
 <tr><th class="left" csk="13" data-stat="team" scope="row"><a href="/teams/jax/2003.htm">Jacksonville Jaguars</a></th><td class="right" data-stat="wins">5</td><td class="right" data-stat="losses">11</td><td class="right" data-stat="win_loss_perc">.313</td><td class="right" data-stat="points">276</td><td class="right" data-stat="points_opp">331</td><td class="right" data-stat="points_diff">-55</td><td class="right" data-stat="mov">-3.4</td><td class="right" data-stat="sos_total">1.0</td><td class="right" data-stat="srs_total">-2.4</td><td class="right" data-stat="srs_offense">-3.3</td><td class="right" data-stat="srs_defense">0.9</td></tr>,
 <tr><th class="left" csk="14" data-stat="team" scope="row"><a href="/teams/htx/2003.htm">Houston Texans</a></th><td class="right" data-stat="wins">5</td><td class="right" data-stat="losses">11</td><td class="right" data-stat="win_loss_perc">.313</td><td class="right" data-stat="points">255</td><td class="right" data-stat="points_opp">380</td><td class="right" data-stat="points_diff">-125</td><td class="right" data-stat="mov">-7.8</td><td class="right" data-stat="sos_total">1.9</td><td class="right" data-stat="srs_total">-6.0</td><td class="right" data-stat="srs_offense">-4.4</td><td class="right" data-stat="srs_defense">-1.5</td></tr>,
 <tr class="thead onecell"><td class="right left" colspan="12" data-stat="onecell"> AFC West</td></tr>,
 <tr><th class="left" csk="16" data-stat="team" scope="row"><a href="/teams/kan/2003.htm">Kansas City Chiefs</a>*</th><td class="right" data-stat="wins">13</td><td class="right" data-stat="losses">3</td><td class="right" data-stat="win_loss_perc">.813</td><td class="right" data-stat="points">484</td><td class="right" data-stat="points_opp">332</td><td class="right" data-stat="points_diff">152</td><td class="right" data-stat="mov">9.5</td><td class="right" data-stat="sos_total">-1.2</td><td class="right" data-stat="srs_total">8.3</td><td class="right" data-stat="srs_offense">9.2</td><td class="right" data-stat="srs_defense">-0.9</td></tr>,
 <tr><th class="left" csk="17" data-stat="team" scope="row"><a href="/teams/den/2003.htm">Denver Broncos</a>+</th><td class="right" data-stat="wins">10</td><td class="right" data-stat="losses">6</td><td class="right" data-stat="win_loss_perc">.625</td><td class="right" data-stat="points">381</td><td class="right" data-stat="points_opp">301</td><td class="right" data-stat="points_diff">80</td><td class="right" data-stat="mov">5.0</td><td class="right" data-stat="sos_total">0.5</td><td class="right" data-stat="srs_total">5.5</td><td class="right" data-stat="srs_offense">2.4</td><td class="right" data-stat="srs_defense">3.1</td></tr>,
 <tr><th class="left" csk="18" data-stat="team" scope="row"><a href="/teams/rai/2003.htm">Oakland Raiders</a></th><td class="right" data-stat="wins">4</td><td class="right" data-stat="losses">12</td><td class="right" data-stat="win_loss_perc">.250</td><td class="right" data-stat="points">270</td><td class="right" data-stat="points_opp">379</td><td class="right" data-stat="points_diff">-109</td><td class="right" data-stat="mov">-6.8</td><td class="right" data-stat="sos_total">1.3</td><td class="right" data-stat="srs_total">-5.5</td><td class="right" data-stat="srs_offense">-4.2</td><td class="right" data-stat="srs_defense">-1.3</td></tr>,
 <tr><th class="left" csk="19" data-stat="team" scope="row"><a href="/teams/sdg/2003.htm">San Diego Chargers</a></th><td class="right" data-stat="wins">4</td><td class="right" data-stat="losses">12</td><td class="right" data-stat="win_loss_perc">.250</td><td class="right" data-stat="points">313</td><td class="right" data-stat="points_opp">441</td><td class="right" data-stat="points_diff">-128</td><td class="right" data-stat="mov">-8.0</td><td class="right" data-stat="sos_total">1.2</td><td class="right" data-stat="srs_total">-6.8</td><td class="right" data-stat="srs_offense">-0.6</td><td class="right" data-stat="srs_defense">-6.2</td></tr>]

In [1]:
import nfl_data_py as nfl

In [2]:
pbp = nfl.import_pbp_data(years=[2003])

2003 done.
Downcasting floats.

In [4]:
coltspbp= pbp[(pbp["posteam"] == 'IND') | (pbp["defteam"] == 'IND')]
coltspbp

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
1077,35.0,2003_01_IND_CLE,2003090702,CLE,IND,REG,1,IND,away,CLE,...,0.0,0.0,1.164213,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1078,57.0,2003_01_IND_CLE,2003090702,CLE,IND,REG,1,IND,away,CLE,...,0.0,0.0,1.010665,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1079,78.0,2003_01_IND_CLE,2003090702,CLE,IND,REG,1,IND,away,CLE,...,0.0,0.0,-0.771268,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1081,116.0,2003_01_IND_CLE,2003090702,CLE,IND,REG,1,IND,away,CLE,...,0.0,0.0,1.716351,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1082,145.0,2003_01_IND_CLE,2003090702,CLE,IND,REG,1,IND,away,CLE,...,0.0,0.0,-0.496155,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46606,4145.0,2003_20_IND_NE,2004011800,NE,IND,POST,20,IND,away,NE,...,0.0,1.0,-0.232258,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46607,4178.0,2003_20_IND_NE,2004011800,NE,IND,POST,20,IND,away,NE,...,0.0,1.0,-0.249339,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46608,4197.0,2003_20_IND_NE,2004011800,NE,IND,POST,20,IND,away,NE,...,1.0,1.0,-0.175322,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46609,4218.0,2003_20_IND_NE,2004011800,NE,IND,POST,20,NE,home,IND,...,0.0,1.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46610,4239.0,2003_20_IND_NE,2004011800,NE,IND,POST,20,NE,home,IND,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
coltspbp = coltspbp.fillna(0)
coltspbp

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
1077,35.0,2003_01_IND_CLE,2003090702,CLE,IND,REG,1,IND,away,CLE,...,0.0,0.0,1.164213,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1078,57.0,2003_01_IND_CLE,2003090702,CLE,IND,REG,1,IND,away,CLE,...,0.0,0.0,1.010665,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1079,78.0,2003_01_IND_CLE,2003090702,CLE,IND,REG,1,IND,away,CLE,...,0.0,0.0,-0.771268,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1081,116.0,2003_01_IND_CLE,2003090702,CLE,IND,REG,1,IND,away,CLE,...,0.0,0.0,1.716351,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1082,145.0,2003_01_IND_CLE,2003090702,CLE,IND,REG,1,IND,away,CLE,...,0.0,0.0,-0.496155,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46606,4145.0,2003_20_IND_NE,2004011800,NE,IND,POST,20,IND,away,NE,...,0.0,1.0,-0.232258,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46607,4178.0,2003_20_IND_NE,2004011800,NE,IND,POST,20,IND,away,NE,...,0.0,1.0,-0.249339,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46608,4197.0,2003_20_IND_NE,2004011800,NE,IND,POST,20,IND,away,NE,...,1.0,1.0,-0.175322,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46609,4218.0,2003_20_IND_NE,2004011800,NE,IND,POST,20,NE,home,IND,...,0.0,1.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46610,4239.0,2003_20_IND_NE,2004011800,NE,IND,POST,20,NE,home,IND,...,0.0,1.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
import pandas as pd
mappings = pd.read_csv("nfl_pbp_column_categories_v3 (1).csv")
mappings

                  column                         category
0                play_id               Identifiers & Meta
1                game_id               Identifiers & Meta
2            old_game_id               Identifiers & Meta
3              home_team                  Teams & Coaches
4              away_team                  Teams & Coaches
..                   ...                              ...
366    xyac_mean_yardage  Advanced Models & Probabilities
367  xyac_median_yardage  Advanced Models & Probabilities
368         xyac_success  Advanced Models & Probabilities
369              xyac_fd  Advanced Models & Probabilities
370                xpass  Advanced Models & Probabilities

[371 rows x 2 columns]

In [10]:
categories = mappings.groupby("category").agg(list).reset_index()
categories

,category,column
0,Admin / Data Quality,[play_deleted]
1,Advanced Models & Probabilities,"[no_score_prob, opp_fg_prob, opp_safety_prob, ..."
2,Betting & Vegas,"[vegas_wpa, vegas_home_wpa, vegas_wp, vegas_ho..."
3,Drive Data,"[drive, fixed_drive, fixed_drive_result, drive..."
4,Environment & Stadium,"[stadium, weather, location, div_game, roof, s..."
5,Fantasy,"[fantasy_player_name, fantasy_player_id, fanta..."
6,Identifiers & Meta,"[play_id, game_id, old_game_id, season_type, w..."
7,Play Classification & Formation,"[play_type, shotgun, no_huddle, qb_dropback, q..."
8,Play Outcomes & Events,"[ydstogo, ydsnet, desc, yards_gained, first_do..."
9,Player Participation – Defense & ST,"[interception_player_id, interception_player_n..."
10,Player Participation – Offense,"[td_player_name, td_player_id, passer_player_i..."
11,Scoring & Score State,"[sp, total_home_score, total_away_score, poste..."
12,Special Teams Outcomes & Attempts,"[field_goal_result, kick_distance, extra_point..."
13,Teams & Coaches,"[home_team, away_team, posteam, posteam_type, ..."
14,Timing & Field Position,"[side_of_field, yardline_100, quarter_seconds_..."

In [11]:
categories.iloc[1][0]

'Advanced Models & Probabilities'

In [29]:
for i in range(categories.shape[0]):
    if i == 0:
        continue
    category = categories.iloc[i][0]
    
    cols = categories.iloc[i][1]
    cur_df = coltspbp[cols]
    cur_df.to_csv(category + "1.csv", index=False)

In [17]:
#weekly stats for each player(offense)

In [16]:
probabilities = pd.read_csv("Advanced Models & Probabilities1.csv")
cols = list(probabilities.columns)
cols

['no_score_prob',
 'opp_fg_prob',
 'opp_safety_prob',
 'opp_td_prob',
 'fg_prob',
 'safety_prob',
 'td_prob',
 'extra_point_prob',
 'two_point_conversion_prob',
 'ep',
 'epa',
 'total_home_epa',
 'total_away_epa',
 'total_home_rush_epa',
 'total_away_rush_epa',
 'total_home_pass_epa',
 'total_away_pass_epa',
 'air_epa',
 'yac_epa',
 'comp_air_epa',
 'comp_yac_epa',
 'total_home_comp_air_epa',
 'total_away_comp_air_epa',
 'total_home_comp_yac_epa',
 'total_away_comp_yac_epa',
 'total_home_raw_air_epa',
 'total_away_raw_air_epa',
 'total_home_raw_yac_epa',
 'total_away_raw_yac_epa',
 'wp',
 'def_wp',
 'home_wp',
 'away_wp',
 'wpa',
 'home_wp_post',
 'away_wp_post',
 'total_home_rush_wpa',
 'total_away_rush_wpa',
 'total_home_pass_wpa',
 'total_away_pass_wpa',
 'air_wpa',
 'yac_wpa',
 'comp_air_wpa',
 'comp_yac_wpa',
 'total_home_comp_air_wpa',
 'total_away_comp_air_wpa',
 'total_home_comp_yac_wpa',
 'total_away_comp_yac_wpa',
 'total_home_raw_air_wpa',
 'total_away_raw_air_wpa',
 'total_home_raw_yac_wpa',
 'total_away_raw_yac_wpa',
 'cp',
 'cpoe',
 'qb_epa',
 'xyac_epa',
 'xyac_mean_yardage',
 'xyac_median_yardage',
 'xyac_success',
 'xyac_fd',
 'xpass']

In [21]:
outcomes = pd.read_csv("Play Outcomes & Events1.csv")
outcomes.head()

,ydstogo,ydsnet,desc,yards_gained,first_down_rush,first_down_pass,first_down_penalty,third_down_converted,third_down_failed,fourth_down_converted,...,penalty_player_id,penalty_player_name,penalty_yards,replay_or_challenge,replay_or_challenge_result,penalty_type,aborted_play,success,first_down,out_of_bounds
0,0.0,60.0,4-P.Dawson kicks 67 yards from CLE 30 to IND 3...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,NaN,0.0,1.0,0.0,0.0
1,10.0,60.0,(14:52) 18-P.Manning pass to 35-R.Williams to ...,9.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,NaN,0.0,1.0,0.0,0.0
2,1.0,60.0,(14:24) 32-E.James right guard to IND 47 for n...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,0.0,0.0
3,1.0,60.0,(13:37) 18-P.Manning pass to 81-M.Pollard to C...,18.0,0.0,1.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,NaN,0.0,1.0,1.0,0.0
4,10.0,60.0,(13:27) (Shotgun) 18-P.Manning pass incomplete...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,0.0,0.0

In [31]:
outcomes = outcomes.fillna(0)

In [36]:
sum_stats = []
not_summed = ["penalty_player_id", "penalty_player_name","replay_or_challenge", "replay_or_challenge_result", "penalty_type"]
for col in list(outcomes.columns):
    if col == 'ydstogo' or col == 'ydsnet' or col == 'desc' or col in not_summed:
        continue
    else:
        sum_stats.append(col)
sum_stats

['yards_gained',
 'first_down_rush',
 'first_down_pass',
 'first_down_penalty',
 'third_down_converted',
 'third_down_failed',
 'fourth_down_converted',
 'fourth_down_failed',
 'incomplete_pass',
 'interception',
 'fumble_forced',
 'fumble_not_forced',
 'fumble_out_of_bounds',
 'solo_tackle',
 'safety',
 'penalty',
 'tackled_for_loss',
 'fumble_lost',
 'qb_hit',
 'rush_attempt',
 'pass_attempt',
 'sack',
 'touchdown',
 'pass_touchdown',
 'rush_touchdown',
 'return_touchdown',
 'fumble',
 'complete_pass',
 'assist_tackle',
 'lateral_reception',
 'lateral_rush',
 'lateral_return',
 'lateral_recovery',
 'penalty_yards',
 'aborted_play',
 'success',
 'first_down',
 'out_of_bounds']

In [37]:
len(sum_stats)

38

In [34]:
coltspbp = coltspbp.fillna(0)

In [38]:
#passing
weekly = coltspbp.groupby(["passer_player_name", "week", "play_type"])[cols].mean().join

In [45]:
passers = coltspbp[coltspbp["passer_player_name"] != 0]

In [48]:
cols.append("ydstogo")

In [62]:
sum_stats[0] = 'passing_yards'

In [63]:
sum_stats

['passing_yards',
 'first_down_rush',
 'first_down_pass',
 'first_down_penalty',
 'third_down_converted',
 'third_down_failed',
 'fourth_down_converted',
 'fourth_down_failed',
 'incomplete_pass',
 'interception',
 'fumble_forced',
 'fumble_not_forced',
 'fumble_out_of_bounds',
 'solo_tackle',
 'safety',
 'penalty',
 'tackled_for_loss',
 'fumble_lost',
 'qb_hit',
 'rush_attempt',
 'pass_attempt',
 'sack',
 'touchdown',
 'pass_touchdown',
 'rush_touchdown',
 'return_touchdown',
 'fumble',
 'complete_pass',
 'assist_tackle',
 'lateral_reception',
 'lateral_rush',
 'lateral_return',
 'lateral_recovery',
 'penalty_yards',
 'aborted_play',
 'success',
 'first_down',
 'out_of_bounds']

In [64]:

weekly_stats = (
    passers.groupby(['passer_player_name',"play_type",'week', 'posteam'])[sum_stats].sum()
    .join(passers.groupby(['passer_player_name',"play_type",'week', 'posteam'])[cols].mean())
    .reset_index()
)

In [65]:
weekly_stats

,passer_player_name,play_type,week,posteam,passing_yards,first_down_rush,first_down_pass,first_down_penalty,third_down_converted,third_down_failed,...,cp,cpoe,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,ydstogo
0,A.Brooks,pass,4,NO,166.0,0.0,8.0,0.0,2.0,4.0,...,0.0,0.0,-0.752571,0.0,0.0,0.0,0.0,0.0,0.0,8.033334
1,B.Griese,pass,9,MIA,231.0,0.0,8.0,0.0,0.0,8.0,...,0.0,0.0,-0.324513,0.0,0.0,0.0,0.0,0.0,0.0,9.000000
2,B.Huard,pass,4,IND,13.0,0.0,1.0,0.0,1.0,1.0,...,0.0,0.0,0.285624,0.0,0.0,0.0,0.0,0.0,0.0,11.000000
3,B.Huard,pass,15,IND,9.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.180409,0.0,0.0,0.0,0.0,0.0,0.0,7.000000
4,B.Huard,pass,18,IND,17.0,0.0,1.0,0.0,1.0,1.0,...,0.0,0.0,-0.465953,0.0,0.0,0.0,0.0,0.0,0.0,8.800000
5,B.Johnson,pass,5,TB,318.0,0.0,14.0,0.0,4.0,6.0,...,0.0,0.0,0.537694,0.0,0.0,0.0,0.0,0.0,0.0,9.473684
6,B.Johnson,qb_spike,5,TB,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.061063,0.0,0.0,0.0,0.0,0.0,0.0,10.000000
7,B.Leftwich,pass,3,JAX,32.0,0.0,2.0,0.0,1.0,0.0,...,0.0,0.0,0.803080,0.0,0.0,0.0,0.0,0.0,0.0,8.000000
8,B.Leftwich,pass,10,JAX,179.0,0.0,8.0,0.0,4.0,3.0,...,0.0,0.0,0.356997,0.0,0.0,0.0,0.0,0.0,0.0,9.545455
9,B.Volek,pass,2,TEN,61.0,0.0,4.0,0.0,2.0,0.0,...,0.0,0.0,-0.926888,0.0,0.0,0.0,0.0,0.0,0.0,7.700000
10,B.Volek,qb_spike,2,TEN,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.158042,0.0,0.0,0.0,0.0,0.0,0.0,10.000000
11,C.Hentrich,pass,2,TEN,10.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,2.710740,0.0,0.0,0.0,0.0,0.0,0.0,1.000000
12,C.Pennington,pass,11,NYJ,219.0,0.0,6.0,0.0,0.0,5.0,...,0.0,0.0,0.481661,0.0,0.0,0.0,0.0,0.0,0.0,10.352942
13,D.Bledsoe,pass,12,BUF,135.0,0.0,5.0,0.0,2.0,9.0,...,0.0,0.0,-0.313863,0.0,0.0,0.0,0.0,0.0,0.0,9.300000
14,D.Carr,pass,8,HOU,62.0,0.0,4.0,0.0,1.0,1.0,...,0.0,0.0,0.255182,0.0,0.0,0.0,0.0,0.0,0.0,9.200000
15,D.Carr,pass,17,HOU,105.0,0.0,5.0,0.0,1.0,8.0,...,0.0,0.0,-0.406815,0.0,0.0,0.0,0.0,0.0,0.0,8.652174
16,D.Johnson,pass,15,ATL,19.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,-0.726634,0.0,0.0,0.0,0.0,0.0,0.0,8.500000
17,J.Delhomme,pass,6,CAR,181.0,0.0,3.0,1.0,1.0,7.0,...,0.0,0.0,0.162373,0.0,0.0,0.0,0.0,0.0,0.0,9.434783
18,J.Plummer,pass,16,DEN,238.0,0.0,11.0,0.0,5.0,2.0,...,0.0,0.0,0.949490,0.0,0.0,0.0,0.0,0.0,0.0,8.352942
19,J.Plummer,pass,18,DEN,181.0,0.0,9.0,0.0,3.0,7.0,...,0.0,0.0,-0.189114,0.0,0.0,0.0,0.0,0.0,0.0,9.156250
20,K.Holcomb,pass,1,CLE,182.0,0.0,9.0,2.0,2.0,6.0,...,0.0,0.0,-0.002415,0.0,0.0,0.0,0.0,0.0,0.0,9.310345
21,L.Toefield,pass,10,JAX,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.685303,0.0,0.0,0.0,0.0,0.0,0.0,7.000000
22,M.Brunell,pass,3,JAX,90.0,0.0,5.0,0.0,1.0,7.0,...,0.0,0.0,-0.189780,0.0,0.0,0.0,0.0,0.0,0.0,9.040000
23,M.Royals,pass,10,JAX,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-3.220480,0.0,0.0,0.0,0.0,0.0,0.0,2.000000
24,M.Vick,pass,15,ATL,47.0,0.0,3.0,0.0,0.0,8.0,...,0.0,0.0,-1.051198,0.0,0.0,0.0,0.0,0.0,0.0,9.347826
25,P. Manning,pass,19,IND,304.0,0.0,17.0,0.0,7.0,0.0,...,0.0,0.0,0.898036,0.0,0.0,0.0,0.0,0.0,0.0,7.870968
26,P. Manning,pass,20,IND,237.0,0.0,13.0,0.0,3.0,9.0,...,0.0,0.0,-0.281669,0.0,0.0,0.0,0.0,0.0,0.0,8.764706
27,P.Manning,pass,1,IND,211.0,0.0,14.0,0.0,6.0,4.0,...,0.0,0.0,-0.056372,0.0,0.0,0.0,0.0,0.0,0.0,8.113636
28,P.Manning,pass,2,IND,173.0,0.0,8.0,0.0,1.0,6.0,...,0.0,0.0,0.176662,0.0,0.0,0.0,0.0,0.0,0.0,9.272727
29,P.Manning,pass,3,IND,216.0,0.0,11.0,0.0,6.0,7.0,...,0.0,0.0,0.144375,0.0,0.0,0.0,0.0,0.0,0.0,8.121212
30,P.Manning,pass,4,IND,314.0,0.0,14.0,0.0,4.0,3.0,...,0.0,0.0,1.052818,0.0,0.0,0.0,0.0,0.0,0.0,8.692307
31,P.Manning,pass,5,IND,386.0,0.0,17.0,1.0,5.0,9.0,...,0.0,0.0,0.365930,0.0,0.0,0.0,0.0,0.0,0.0,9.458333
32,P.Manning,pass,6,IND,293.0,0.0,15.0,0.0,1.0,6.0,...,0.0,0.0,0.236788,0.0,0.0,0.0,0.0,0.0,0.0,8.176471
33,P.Manning,pass,8,IND,269.0,0.0,14.0,0.0,3.0,5.0,...,0.0,0.0,0.471836,0.0,0.0,0.0,0.0,0.0,0.0,7.533333
34,P.Manning,pass,9,IND,266.0,0.0,13.0,2.0,5.0,9.0,...,0.0,0.0,0.135591,0.0,0.0,0.0,0.0,0.0,0.0,8.853659
35,P.Manning,pass,10,IND,347.0,0.0,16.0,2.0,6.0,9.0,...,0.0,0.0,0.409169,0.0,0.0,0.0,0.0,0.0,0.0,7.933333
36,P.Manning,pass,11,IND,401.0,0.0,17.0,0.0,5.0,4.0,...,0.0,0.0,0.464813,0.0,0.0,0.0,0.0,0.0,0.0,7.918919
37,P.Manning,pass,12,IND,229.0,0.0,13.0,0.0,7.0,7.0,...,0.0,0.0,0.094697,0.0,0.0,0.0,0.0,0.0,0.0,7.431818
38,P.Manning,pass,13,IND,278.0,0.0,14.0,0.0,5.0,10.0,...,0.0,0.0,0.066584,0.0,0.0,0.0,0.0,0.0,0.0,8.460000
39,P.Manning,pass,14,IND,228.0,0.0,10.0,1.0,2.0,8.0,...,0.0,0.0,0.066412,0.0,0.0,0.0,0.0,0.0,0.0,8.864865
40,P.Manning,pass,15,IND,290.0,0.0,17.0,0.0,5.0,3.0,...,0.0,0.0,0.678701,0.0,0.0,0.0,0.0,0.0,0.0,8.032258
41,P.Manning,pass,16,IND,146.0,0.0,4.0,1.0,0.0,7.0,...,0.0,0.0,-0.283539,0.0,0.0,0.0,0.0,0.0,0.0,10.160000
42,P.Manning,pass,17,IND,220.0,0.0,13.0,0.0,5.0,6.0,...,0.0,0.0,-0.027419,0.0,0.0,0.0,0.0,0.0,0.0,9.000000
43,P.Manning,pass,18,IND,377.0,0.0,16.0,0.0,5.0,1.0,...,0.0,0.0,1.147174,0.0,0.0,0.0,0.0,0.0,0.0,8.153846
44,S.McNair,pass,2,TEN,138.0,0.0,6.0,0.0,2.0,8.0,...,0.0,0.0,-0.303594,0.0,0.0,0.0,0.0,0.0,0.0,9.370370
45,S.McNair,pass,14,TEN,235.0,0.0,15.0,1.0,5.0,3.0,...,0.0,0.0,0.325780,0.0,0.0,0.0,0.0,0.0,0.0,8.300000
46,T. Green,pass,19,KC,212.0,0.0,13.0,0.0,3.0,4.0,...,0.0,0.0,0.518681,0.0,0.0,0.0,0.0,0.0,0.0,8.233334
47,T.Banks,pass,8,HOU,88.0,0.0,4.0,0.0,2.0,3.0,...,0.0,0.0,-0.072788,0.0,0.0,0.0,0.0,0.0,0.0,9.000000
48,T.Banks,qb_spike,8,HOU,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.021989,0.0,0.0,0.0,0.0,0.0,0.0,10.000000
49,T.Bouman,pass,4,NO,62.0,0.0,4.0,0.0,2.0,1.0,...,0.0,0.0,0.616430,0.0,0.0,0.0,0.0,0.0,0.0,8.666667
50,T.Brady,pass,13,NE,236.0,0.0,12.0,0.0,4.0,4.0,...,0.0,0.0,0.134703,0.0,0.0,0.0,0.0,0.0,0.0,9.027027
51,T.Brady,pass,20,NE,237.0,0.0,15.0,0.0,4.0,7.0,...,0.0,0.0,0.088522,0.0,0.0,0.0,0.0,0.0,0.0,7.783784

In [66]:
INDpasser_stats = weekly_stats[weekly_stats["posteam"] == 'IND'].reset_index(drop=True)
opppasser_stats = weekly_stats[weekly_stats["posteam"] != 'IND'].reset_index(drop=True)

In [67]:
INDpasser_stats

,passer_player_name,play_type,week,posteam,passing_yards,first_down_rush,first_down_pass,first_down_penalty,third_down_converted,third_down_failed,...,cp,cpoe,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,ydstogo
0,B.Huard,pass,4,IND,13.0,0.0,1.0,0.0,1.0,1.0,...,0.0,0.0,0.285624,0.0,0.0,0.0,0.0,0.0,0.0,11.000000
1,B.Huard,pass,15,IND,9.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.180409,0.0,0.0,0.0,0.0,0.0,0.0,7.000000
2,B.Huard,pass,18,IND,17.0,0.0,1.0,0.0,1.0,1.0,...,0.0,0.0,-0.465953,0.0,0.0,0.0,0.0,0.0,0.0,8.800000
3,P. Manning,pass,19,IND,304.0,0.0,17.0,0.0,7.0,0.0,...,0.0,0.0,0.898036,0.0,0.0,0.0,0.0,0.0,0.0,7.870968
4,P. Manning,pass,20,IND,237.0,0.0,13.0,0.0,3.0,9.0,...,0.0,0.0,-0.281669,0.0,0.0,0.0,0.0,0.0,0.0,8.764706
5,P.Manning,pass,1,IND,211.0,0.0,14.0,0.0,6.0,4.0,...,0.0,0.0,-0.056372,0.0,0.0,0.0,0.0,0.0,0.0,8.113636
6,P.Manning,pass,2,IND,173.0,0.0,8.0,0.0,1.0,6.0,...,0.0,0.0,0.176662,0.0,0.0,0.0,0.0,0.0,0.0,9.272727
7,P.Manning,pass,3,IND,216.0,0.0,11.0,0.0,6.0,7.0,...,0.0,0.0,0.144375,0.0,0.0,0.0,0.0,0.0,0.0,8.121212
8,P.Manning,pass,4,IND,314.0,0.0,14.0,0.0,4.0,3.0,...,0.0,0.0,1.052818,0.0,0.0,0.0,0.0,0.0,0.0,8.692307
9,P.Manning,pass,5,IND,386.0,0.0,17.0,1.0,5.0,9.0,...,0.0,0.0,0.365930,0.0,0.0,0.0,0.0,0.0,0.0,9.458333
10,P.Manning,pass,6,IND,293.0,0.0,15.0,0.0,1.0,6.0,...,0.0,0.0,0.236788,0.0,0.0,0.0,0.0,0.0,0.0,8.176471
11,P.Manning,pass,8,IND,269.0,0.0,14.0,0.0,3.0,5.0,...,0.0,0.0,0.471836,0.0,0.0,0.0,0.0,0.0,0.0,7.533333
12,P.Manning,pass,9,IND,266.0,0.0,13.0,2.0,5.0,9.0,...,0.0,0.0,0.135591,0.0,0.0,0.0,0.0,0.0,0.0,8.853659
13,P.Manning,pass,10,IND,347.0,0.0,16.0,2.0,6.0,9.0,...,0.0,0.0,0.409169,0.0,0.0,0.0,0.0,0.0,0.0,7.933333
14,P.Manning,pass,11,IND,401.0,0.0,17.0,0.0,5.0,4.0,...,0.0,0.0,0.464813,0.0,0.0,0.0,0.0,0.0,0.0,7.918919
15,P.Manning,pass,12,IND,229.0,0.0,13.0,0.0,7.0,7.0,...,0.0,0.0,0.094697,0.0,0.0,0.0,0.0,0.0,0.0,7.431818
16,P.Manning,pass,13,IND,278.0,0.0,14.0,0.0,5.0,10.0,...,0.0,0.0,0.066584,0.0,0.0,0.0,0.0,0.0,0.0,8.460000
17,P.Manning,pass,14,IND,228.0,0.0,10.0,1.0,2.0,8.0,...,0.0,0.0,0.066412,0.0,0.0,0.0,0.0,0.0,0.0,8.864865
18,P.Manning,pass,15,IND,290.0,0.0,17.0,0.0,5.0,3.0,...,0.0,0.0,0.678701,0.0,0.0,0.0,0.0,0.0,0.0,8.032258
19,P.Manning,pass,16,IND,146.0,0.0,4.0,1.0,0.0,7.0,...,0.0,0.0,-0.283539,0.0,0.0,0.0,0.0,0.0,0.0,10.160000
20,P.Manning,pass,17,IND,220.0,0.0,13.0,0.0,5.0,6.0,...,0.0,0.0,-0.027419,0.0,0.0,0.0,0.0,0.0,0.0,9.000000
21,P.Manning,pass,18,IND,377.0,0.0,16.0,0.0,5.0,1.0,...,0.0,0.0,1.147174,0.0,0.0,0.0,0.0,0.0,0.0,8.153846

In [68]:
opppasser_stats

,passer_player_name,play_type,week,posteam,passing_yards,first_down_rush,first_down_pass,first_down_penalty,third_down_converted,third_down_failed,...,cp,cpoe,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,ydstogo
0,A.Brooks,pass,4,NO,166.0,0.0,8.0,0.0,2.0,4.0,...,0.0,0.0,-0.752571,0.0,0.0,0.0,0.0,0.0,0.0,8.033334
1,B.Griese,pass,9,MIA,231.0,0.0,8.0,0.0,0.0,8.0,...,0.0,0.0,-0.324513,0.0,0.0,0.0,0.0,0.0,0.0,9.000000
2,B.Johnson,pass,5,TB,318.0,0.0,14.0,0.0,4.0,6.0,...,0.0,0.0,0.537694,0.0,0.0,0.0,0.0,0.0,0.0,9.473684
3,B.Johnson,qb_spike,5,TB,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.061063,0.0,0.0,0.0,0.0,0.0,0.0,10.000000
4,B.Leftwich,pass,3,JAX,32.0,0.0,2.0,0.0,1.0,0.0,...,0.0,0.0,0.803080,0.0,0.0,0.0,0.0,0.0,0.0,8.000000
5,B.Leftwich,pass,10,JAX,179.0,0.0,8.0,0.0,4.0,3.0,...,0.0,0.0,0.356997,0.0,0.0,0.0,0.0,0.0,0.0,9.545455
6,B.Volek,pass,2,TEN,61.0,0.0,4.0,0.0,2.0,0.0,...,0.0,0.0,-0.926888,0.0,0.0,0.0,0.0,0.0,0.0,7.700000
7,B.Volek,qb_spike,2,TEN,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.158042,0.0,0.0,0.0,0.0,0.0,0.0,10.000000
8,C.Hentrich,pass,2,TEN,10.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,2.710740,0.0,0.0,0.0,0.0,0.0,0.0,1.000000
9,C.Pennington,pass,11,NYJ,219.0,0.0,6.0,0.0,0.0,5.0,...,0.0,0.0,0.481661,0.0,0.0,0.0,0.0,0.0,0.0,10.352942
10,D.Bledsoe,pass,12,BUF,135.0,0.0,5.0,0.0,2.0,9.0,...,0.0,0.0,-0.313863,0.0,0.0,0.0,0.0,0.0,0.0,9.300000
11,D.Carr,pass,8,HOU,62.0,0.0,4.0,0.0,1.0,1.0,...,0.0,0.0,0.255182,0.0,0.0,0.0,0.0,0.0,0.0,9.200000
12,D.Carr,pass,17,HOU,105.0,0.0,5.0,0.0,1.0,8.0,...,0.0,0.0,-0.406815,0.0,0.0,0.0,0.0,0.0,0.0,8.652174
13,D.Johnson,pass,15,ATL,19.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,-0.726634,0.0,0.0,0.0,0.0,0.0,0.0,8.500000
14,J.Delhomme,pass,6,CAR,181.0,0.0,3.0,1.0,1.0,7.0,...,0.0,0.0,0.162373,0.0,0.0,0.0,0.0,0.0,0.0,9.434783
15,J.Plummer,pass,16,DEN,238.0,0.0,11.0,0.0,5.0,2.0,...,0.0,0.0,0.949490,0.0,0.0,0.0,0.0,0.0,0.0,8.352942
16,J.Plummer,pass,18,DEN,181.0,0.0,9.0,0.0,3.0,7.0,...,0.0,0.0,-0.189114,0.0,0.0,0.0,0.0,0.0,0.0,9.156250
17,K.Holcomb,pass,1,CLE,182.0,0.0,9.0,2.0,2.0,6.0,...,0.0,0.0,-0.002415,0.0,0.0,0.0,0.0,0.0,0.0,9.310345
18,L.Toefield,pass,10,JAX,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.685303,0.0,0.0,0.0,0.0,0.0,0.0,7.000000
19,M.Brunell,pass,3,JAX,90.0,0.0,5.0,0.0,1.0,7.0,...,0.0,0.0,-0.189780,0.0,0.0,0.0,0.0,0.0,0.0,9.040000
20,M.Royals,pass,10,JAX,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-3.220480,0.0,0.0,0.0,0.0,0.0,0.0,2.000000
21,M.Vick,pass,15,ATL,47.0,0.0,3.0,0.0,0.0,8.0,...,0.0,0.0,-1.051198,0.0,0.0,0.0,0.0,0.0,0.0,9.347826
22,S.McNair,pass,2,TEN,138.0,0.0,6.0,0.0,2.0,8.0,...,0.0,0.0,-0.303594,0.0,0.0,0.0,0.0,0.0,0.0,9.370370
23,S.McNair,pass,14,TEN,235.0,0.0,15.0,1.0,5.0,3.0,...,0.0,0.0,0.325780,0.0,0.0,0.0,0.0,0.0,0.0,8.300000
24,T. Green,pass,19,KC,212.0,0.0,13.0,0.0,3.0,4.0,...,0.0,0.0,0.518681,0.0,0.0,0.0,0.0,0.0,0.0,8.233334
25,T.Banks,pass,8,HOU,88.0,0.0,4.0,0.0,2.0,3.0,...,0.0,0.0,-0.072788,0.0,0.0,0.0,0.0,0.0,0.0,9.000000
26,T.Banks,qb_spike,8,HOU,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.021989,0.0,0.0,0.0,0.0,0.0,0.0,10.000000
27,T.Bouman,pass,4,NO,62.0,0.0,4.0,0.0,2.0,1.0,...,0.0,0.0,0.616430,0.0,0.0,0.0,0.0,0.0,0.0,8.666667
28,T.Brady,pass,13,NE,236.0,0.0,12.0,0.0,4.0,4.0,...,0.0,0.0,0.134703,0.0,0.0,0.0,0.0,0.0,0.0,9.027027
29,T.Brady,pass,20,NE,237.0,0.0,15.0,0.0,4.0,7.0,...,0.0,0.0,0.088522,0.0,0.0,0.0,0.0,0.0,0.0,7.783784

In [70]:
sum_stats2 = sum_stats
sum_stats2[0] = 'rushing_yards'
sum_stats2

['rushing_yards',
 'first_down_rush',
 'first_down_pass',
 'first_down_penalty',
 'third_down_converted',
 'third_down_failed',
 'fourth_down_converted',
 'fourth_down_failed',
 'incomplete_pass',
 'interception',
 'fumble_forced',
 'fumble_not_forced',
 'fumble_out_of_bounds',
 'solo_tackle',
 'safety',
 'penalty',
 'tackled_for_loss',
 'fumble_lost',
 'qb_hit',
 'rush_attempt',
 'pass_attempt',
 'sack',
 'touchdown',
 'pass_touchdown',
 'rush_touchdown',
 'return_touchdown',
 'fumble',
 'complete_pass',
 'assist_tackle',
 'lateral_reception',
 'lateral_rush',
 'lateral_return',
 'lateral_recovery',
 'penalty_yards',
 'aborted_play',
 'success',
 'first_down',
 'out_of_bounds']

In [73]:
rushers = coltspbp[coltspbp["rusher_player_name"] != 0]

In [88]:
#rushing
rushing_stats = (
    rushers.groupby(['rusher_player_name',"play_type",'week', 'posteam'])[sum_stats2].sum()
    .join(rushers.groupby(['rusher_player_name',"play_type",'week', 'posteam'])[cols].mean())
    .reset_index()
)

In [75]:
rushing_stats

,rusher_player_name,play_type,week,posteam,rushing_yards,first_down_rush,first_down_pass,first_down_penalty,third_down_converted,third_down_failed,...,cp,cpoe,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,ydstogo
0,A.Brooks,run,4,NO,9.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,-0.517141,0.0,0.0,0.0,0.0,0.0,0.0,9.000000
1,A.Smith,run,20,NE,100.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.124213,0.0,0.0,0.0,0.0,0.0,0.0,8.227273
2,A.Stecker,run,5,TB,22.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,-0.441475,0.0,0.0,0.0,0.0,0.0,0.0,11.555555
3,B.Huard,run,4,IND,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-1.061953,0.0,0.0,0.0,0.0,0.0,0.0,11.000000
4,B.Huard,run,15,IND,9.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.209059,0.0,0.0,0.0,0.0,0.0,0.0,12.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,T.Jones,run,5,TB,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.401683,0.0,0.0,0.0,0.0,0.0,0.0,6.000000
141,T.Minor,run,9,MIA,11.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.815576,0.0,0.0,0.0,0.0,0.0,0.0,3.000000
142,T.Walters,run,9,IND,6.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.165376,0.0,0.0,0.0,0.0,0.0,0.0,10.000000
143,Team,qb_kneel,4,IND,-1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-3.051928,0.0,0.0,0.0,0.0,0.0,0.0,10.000000
144,W.Green,run,1,CLE,86.0,6.0,0.0,0.0,2.0,1.0,...,0.0,0.0,-0.085175,0.0,0.0,0.0,0.0,0.0,0.0,7.095238

In [78]:
INDrushing_stats = rushing_stats[rushing_stats["posteam"] == "IND"].reset_index(drop=True)
opprushing_stats = rushing_stats[rushing_stats["posteam"] != "IND"].reset_index(drop=True)

In [79]:
INDrushing_stats
opprushing_stats

,rusher_player_name,play_type,week,posteam,rushing_yards,first_down_rush,first_down_pass,first_down_penalty,third_down_converted,third_down_failed,...,cp,cpoe,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,ydstogo
0,A.Brooks,run,4,NO,9.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,-0.517141,0.0,0.0,0.0,0.0,0.0,0.0,9.000000
1,A.Smith,run,20,NE,100.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.124213,0.0,0.0,0.0,0.0,0.0,0.0,8.227273
2,A.Stecker,run,5,TB,22.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,-0.441475,0.0,0.0,0.0,0.0,0.0,0.0,11.555555
3,B.Johnson,run,5,TB,8.0,1.0,0.0,0.0,1.0,1.0,...,0.0,0.0,-0.322359,0.0,0.0,0.0,0.0,0.0,0.0,4.666667
4,B.Johnson,run,20,NE,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.277684,0.0,0.0,0.0,0.0,0.0,0.0,4.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,T.Duckett,run,15,ATL,74.0,4.0,0.0,0.0,0.0,1.0,...,0.0,0.0,-0.042657,0.0,0.0,0.0,0.0,0.0,0.0,8.055555
78,T.Henry,run,12,BUF,77.0,6.0,0.0,1.0,0.0,1.0,...,0.0,0.0,-0.015455,0.0,0.0,0.0,0.0,0.0,0.0,8.227273
79,T.Jones,run,5,TB,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.401683,0.0,0.0,0.0,0.0,0.0,0.0,6.000000
80,T.Minor,run,9,MIA,11.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.815576,0.0,0.0,0.0,0.0,0.0,0.0,3.000000
81,W.Green,run,1,CLE,86.0,6.0,0.0,0.0,2.0,1.0,...,0.0,0.0,-0.085175,0.0,0.0,0.0,0.0,0.0,0.0,7.095238

In [80]:
INDrushing_stats

,rusher_player_name,play_type,week,posteam,rushing_yards,first_down_rush,first_down_pass,first_down_penalty,third_down_converted,third_down_failed,...,cp,cpoe,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,ydstogo
0,B.Huard,run,4,IND,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-1.061953,0.0,0.0,0.0,0.0,0.0,0.0,11.000000
1,B.Huard,run,15,IND,9.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.209059,0.0,0.0,0.0,0.0,0.0,0.0,12.000000
2,D. Rhodes,run,19,IND,18.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,-0.197962,0.0,0.0,0.0,0.0,0.0,0.0,6.400000
3,D. Rhodes,run,20,IND,16.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.101144,0.0,0.0,0.0,0.0,0.0,0.0,10.000000
4,D.Rhodes,run,4,IND,36.0,2.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.214105,0.0,0.0,0.0,0.0,0.0,0.0,6.833333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,R.Williams,run,10,IND,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.472866,0.0,0.0,0.0,0.0,0.0,0.0,9.833333
59,R.Williams,run,15,IND,-2.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.162260,0.0,0.0,0.0,0.0,0.0,0.0,10.000000
60,R.Williams,run,18,IND,-1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-0.878992,0.0,0.0,0.0,0.0,0.0,0.0,10.000000
61,T.Walters,run,9,IND,6.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.165376,0.0,0.0,0.0,0.0,0.0,0.0,10.000000
62,Team,qb_kneel,4,IND,-1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-3.051928,0.0,0.0,0.0,0.0,0.0,0.0,10.000000

In [84]:
#receivers
receivers = coltspbp[coltspbp["receiver_player_name"] != 0]

In [85]:
sum_stats3 = sum_stats
sum_stats3[0] = "receiving_yards"

In [87]:
receiving_stats = (
    receivers.groupby(['receiver_player_name',"play_type",'week', 'posteam'])[sum_stats3].sum()
    .join(rushers.groupby(['rusher_player_name',"play_type",'week', 'posteam'])[cols].mean())
    .reset_index()
)

In [90]:
INDreceiving_stats = receiving_stats[receiving_stats["posteam"] == "IND"].reset_index(drop=True)
oppreceiving_stats = receiving_stats[receiving_stats["posteam"] != "IND"].reset_index(drop=True)

In [ ]:
INDreceiving_stats.to_csv("INDreceiving_stats1.csv")
oppreceiving_stats.to_csv("oppreceiving_stats1.csv")
INDrushing_stats.to_csv("INDrushing_weekly_stats1.csv")
opprushing_stats.to_csv("opprushing_weekly_stats1.csv")
INDpasser_stats.to_csv("INDpassing_weekly_stats1.csv")
opppasser_stats.to_csv("opppassing_weeklystats1.csv")

In [3]:
import tensorflow as tf

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [4]:
pip show tensorflow

Name: tensorflow
Version: 2.19.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /anaconda/envs/azureml_py38/lib/python3.10/site-packages
Requires: absl-py, astunparse, flatbuffers, gast, google-pasta, grpcio, h5py, keras, libclang, ml-dtypes, numpy, opt-einsum, packaging, protobuf, requests, setuptools, six, tensorboard, tensorflow-io-gcs-filesystem, termcolor, typing-extensions, wrapt
Required-by: tensorflow-text
Note: you may need to restart the kernel to use updated packages.

In [6]:
import tensorflow as tf, numpy as np
print("TensorFlow:", tf.__version__)
print("NumPy:", np.__version__)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [12]:
import numpy as np
print("NumPy:", np.__version__)

NumPy: 1.23.5

In [9]:
import sys
print(sys.executable)

/anaconda/envs/azureml_py38/bin/python

In [13]:
import sys, numpy
print("Python executable:", sys.executable)
print("NumPy location:", numpy.__file__)
print("NumPy version:", numpy.__version__)

Python executable: /anaconda/envs/azureml_py38/bin/python
NumPy location: /anaconda/envs/azureml_py38/lib/python3.10/site-packages/numpy/__init__.py
NumPy version: 1.23.5